package user

import (
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"strings"

	"git.rpjosh.de/RPJosh/go-logger"
	"git.rpjosh.de/RPJosh/workout/internal/models"
	"git.rpjosh.de/RPJosh/workout/pkg/database"
	"git.rpjosh.de/RPJosh/workout/pkg/database/dbstruct"
	"git.rpjosh.de/RPJosh/workout/pkg/errors"
	"git.rpjosh.de/RPJosh/workout/pkg/utils"
	"golang.org/x/crypto/argon2"
)

// Argon default parameters
const (
	ArgonSaltLength  = 16
	ArgonThreads     = 2
	ArgonMemoryCosts = 2048
	ArgonTimeCosts   = 3
	ArgonKeyLength   = 32
)

// Errors for this function
var (
	ErrInvalidHash         = errors.New("the encoded hash is not in the correct format")
	ErrIncompatibleVersion = errors.New("incompatible version of argon2")
	ErrUserNotFound        = errors.NewError("#login.passwordIncorrect", 403)
	ErrPasswordIncorrect   = errors.NewError("#login.passwordIncorrect", 403)
	ErrUserExists          = errors.NewError("#user.exists", 409)
)

// argonParams represents options used for argon2 password hashing
type argonParams struct {
	memory      uint32
	iterations  uint32
	parallelism uint8
	saltLength  uint32
	keyLength   uint32
}

// IsLoginCorrect checks whether the username and password
// of the user are correct.
// If the user was found, the ID will be returned
func (api *Api) IsLoginCorrect(mail, password string) (int, errors.Error) {
	// Get the user for which the user want's to authenticate himselve
	user := models.User{}
	quer := api.R().Db.Struct.Query(&user)
	quer.Where().Column(models.User_Mail, "=", mail).IgnoreCase(true).Add()
	if err := quer.Run(); err != nil {
		// No user found
		if err.Type() == database.NoRows {
			return 0, ErrUserNotFound
		} else {
			// Unknown error
			return 0, errors.InternalError().Log("", err, api)
		}
	}

	// Compare passwords
	passwordCorrect, err := api.comparePassword(password, user.Password)
	if err != nil {
		return 0, errors.InternalError().Log("Failed to compare password for user %d", err, api, user.Id)
	}

	if !passwordCorrect {
		return 0, ErrPasswordIncorrect
	}

	return user.Id, nil
}

// CreateUser creates the given user in the database
func (api *Api) CreateUser(user models.User) errors.Error {
	var er error

	// Mail is lowercased
	user.Mail = strings.ToLower(user.Mail)

	// User mustn't exist
	existingUsers := 0
	err := api.R().Db.QueryForValue(
		&existingUsers,
		`SELECT COUNT(*) FROM user where mail = ?`, user.Mail,
	)
	if err != nil {
		return errors.InternalError()
	}
	if existingUsers != 0 {
		return ErrUserExists
	}

	// Hash password
	user.Password, er = api.hashUserPassword(user.Password)
	if er != nil {
		logger.Warning("Failed to hash user password: %s", err)
		return errors.InternalError()
	}

	// Insert user into database
	if _, er = api.R().Db.Struct.Insert(&user).Run(); er != nil {
		logger.Warning("Failed to insert user: %s", err)
		return errors.InternalError()
	}

	return nil
}

// hashUserPassword hashes the provided password of the user
// with the argon2 algorithm
func (api *Api) hashUserPassword(password string) (string, error) {
	// Generate a cryptographically secure random salt
	salt, err := utils.GenerateRandomBytes(ArgonSaltLength)
	if err != nil {
		return "", fmt.Errorf("failed to generate salt: %w", err)
	}

	// Generate hash value
	hash := argon2.IDKey([]byte(password), salt, ArgonTimeCosts, ArgonMemoryCosts, ArgonThreads, ArgonKeyLength)

	// Base64 encode the salt and hashed password.
	b64Salt := base64.RawStdEncoding.EncodeToString(salt)
	b64Hash := base64.RawStdEncoding.EncodeToString(hash)

	// Return a string that stores the parameters used for hashing
	return fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s", argon2.Version, ArgonMemoryCosts, ArgonTimeCosts, ArgonThreads, b64Salt, b64Hash), nil
}

// comparePassword compares the raw password from the user
// with the provided hash.
// The hash has to be generated by [hashUserPassword]
func (api *Api) comparePassword(password, encodedHash string) (match bool, err error) {
	// Extract the parameters from the hash
	p, salt, hash, err := api.decodeHash(encodedHash)
	if err != nil {
		return false, err
	}

	// Derive the key from the other password using the same parameters
	otherHash := argon2.IDKey([]byte(password), salt, p.iterations, p.memory, p.parallelism, p.keyLength)

	// Check that the contents of the hashed passwords are identical.
	// subtle.ConstantTimeCompare() is used to prevent timing attacks
	if subtle.ConstantTimeCompare(hash, otherHash) == 1 {
		return true, nil
	}
	return false, nil
}

func (api *Api) decodeHash(encodedHash string) (p *argonParams, salt, hash []byte, err error) {
	vals := strings.Split(encodedHash, "$")
	if len(vals) != 6 {
		return nil, nil, nil, ErrInvalidHash
	}

	var version int
	_, err = fmt.Sscanf(vals[2], "v=%d", &version)
	if err != nil {
		return nil, nil, nil, err
	}
	if version != argon2.Version {
		return nil, nil, nil, ErrIncompatibleVersion
	}

	p = &argonParams{}
	_, err = fmt.Sscanf(vals[3], "m=%d,t=%d,p=%d", &p.memory, &p.iterations, &p.parallelism)
	if err != nil {
		return nil, nil, nil, err
	}

	salt, err = base64.RawStdEncoding.Strict().DecodeString(vals[4])
	if err != nil {
		return nil, nil, nil, err
	}
	p.saltLength = uint32(len(salt))

	hash, err = base64.RawStdEncoding.Strict().DecodeString(vals[5])
	if err != nil {
		return nil, nil, nil, err
	}
	p.keyLength = uint32(len(hash))

	return p, salt, hash, nil
}

// UpdateProperty updates the provided properties / fields for the given user
func (api *Api) UpdateProperty(user models.User, properties ...string) errors.Error {
	// Only update provided properties
	sel := dbstruct.ColumnSelector{
		IncludeColumns: properties,
	}

	// Run the update
	if err := api.R().Db.Struct.Update(&user).Selector(sel).Run(); err != nil {
		logger.Warning("Failed to update user: %s", err)
		return errors.InternalError()
	}

	return nil
}
