package database

import (
	"fmt"
	"reflect"
	"strings"

	"git.rpjosh.de/RPJosh/go-ddl-parser/structt"
	"git.rpjosh.de/RPJosh/go-logger"
	"git.rpjosh.de/RPJosh/go-webserver/errors"
)

// StructOperator contains extended functions for "DatabaseUtils"
// to query, update or delete structs generated by "go-ddl-parser"
// or manually tagged structs
type StructOperator struct {
	// Internal reference to the DatabaseUtils
	dbUtils *DatabaseUtils
}

type Query struct {

	// Internal reference to an operator
	operator *StructOperator

	// The destination type is an array instead
	// of a single struct
	isArray bool

	// Destination to write the result to:
	//  - Single value: pointer to a struct (*struct)
	//  - Multiple values: array of structs ([]struct)
	dst reflect.Value

	// Type of the struct to write the data to (single + multiple)
	typ reflect.Type

	// The last occured error will be stored in this fild and is
	// only returned in "Run()".
	// If any error occured, the (internal) processing is stopped
	err DatabaseError

	// Fields to exclude to query
	columnSelector ColumnSelector

	// Weather the selector was set
	customSelector bool

	// Custom where statement
	whereStatement string
	// Placeholders for the where statement
	wherePlaceholder []any
}

// ColumnSelector specifies which columns should be selected or updated
type ColumnSelector struct {

	// Only include the specified columns.
	// The value should be a const expressiong generated by go-ddl
	IncludeColumns []string

	// Columns to exclude
	ExcludeColumns []string

	// Weather to include foreignKeyReferences (1:1 relationships).
	//   - Select: enabled by default
	//   - Insert: Ignored even if this value is "true"
	//   - Update: Ignored even if this value is "true"
	ForeignKeyReference bool

	// Weather to include columns from which this table was referenced
	// from (n:1 relationships)
	PointedKeyReference bool

	// Weather primary keys should always be parsed
	includePrimaryKeys bool
}

// Where contains data for a specific where statement
type Where struct {

	// Internal reference to the query
	query *Query

	// Operator like "=", ">", "<", ...
	operator string

	// Column name to select
	column string

	// Value to insert as a placeholder
	val any

	// Ignore the case
	ignoreCase bool
}

type table struct {

	// Generic table information
	structt.MetadataTag

	// Type of this struct
	typ reflect.Type

	// Columns of this table
	columns []column

	// Only for level zero and multiple (embedded) tables
	fieldName string
}

type column struct {

	// Generic column information
	structt.ColumnTag

	// Position of the field within struct type
	position int

	// Table that is referenced by this column. It's filled when:
	//   - isForeignKeyReference = treu
	//   - [structt.ColumnTag.PointedKeyReference != ""]
	foreignKeyTable *table

	// Weather this field points to another struct that
	// is referenced via a foreign key.
	// We need this additional field besides [structt.ColumnTag.ForeignKeyReference] to
	// check if the go ddl-parser actually used a full struct instead
	// of only the primary key from the referenced table
	isForeignKeyReference bool

	// Name of the struct field the column is assigned to
	fieldName string
}

// Query analyzes the provided struct and selects all fields tagged
// with "dbColumn" from one or multiple tables and writes the result
// into *dst.
// If *dst is a nil pointer, the underlaying value to which the pointer points
// to will be initialized
//
// Exactly a single row is expected to be returned from the database.
func (d *StructOperator) Query(dst any) *Query {
	rtc := &Query{
		operator: d,
	}

	// Validate given type
	dstVal := reflect.ValueOf(dst)
	if err := isPointer(dstVal, reflect.Struct); err != nil {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for dst given: %s", err),
			Response: errors.InternalError(),
		}
	}
	rtc.dst = dstVal
	rtc.typ = reflect.TypeOf(dst).Elem()

	return rtc
}

// QuerySlice is like [Query] but writes multiple rows from the database
// to an array (*[]dst).
func (d *StructOperator) QuerySlice(dst any) *Query {
	rtc := &Query{
		isArray:  true,
		operator: d,
	}

	// Make sure that we got a slice
	dstType := reflect.TypeOf(dst)
	if dstType.Kind() != reflect.Pointer || dstType.Elem().Kind() != reflect.Slice || dstType.Elem().Elem().Kind() != reflect.Struct {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("expected a pointer to a slice containing structs for dst"),
			Response: errors.InternalError(),
		}
		return rtc
	}
	rtc.dst = reflect.ValueOf(dst).Elem()
	rtc.typ = dstType.Elem().Elem()

	return rtc
}

// Selector adds an column selector for the query
func (q *Query) Selector(selector ColumnSelector) *Query {
	q.columnSelector = selector
	q.customSelector = true
	return q
}

// parseField parses all fields of the provided struct{}.
// For a level != 0 this function always returns a single table
func (s ColumnSelector) parseField(val reflect.Type, level int, structField string) (tbl []table, e error) {

	// Table structs are identified by the metadata field
	if f, found := val.FieldByName(structt.MetadataFieldName); found {
		valTag, ok := f.Tag.Lookup(structt.MetadataTagId)
		if !ok {
			e = fmt.Errorf("no tag found for metadata in %s", val)
			return
		}

		// Tbl metadata
		tbl := table{
			MetadataTag: *structt.FromMetadataTag(valTag),
			typ:         val,
			fieldName:   structField,
		}

		for i := 0; i < val.NumField(); i++ {
			field := val.Field(i)

			// Get tag
			valTag, ok := field.Tag.Lookup(structt.ColumnTagId)
			if !ok {
				continue
			}

			col := column{
				ColumnTag: *structt.FromColumnTag(valTag),
				position:  i,
				fieldName: field.Name,
			}

			// Check if column is ignored
			if s.isFieldIgnored(&tbl, &col) {
				continue
			}

			// Set any foreign key reference
			if col.ColumnTag.ForeignKeyReference != "" && s.isTableStruct(field.Type) {
				col.isForeignKeyReference = col.ColumnTag.ForeignKeyReference != ""
				tbll, err := s.parseField(field.Type.Elem(), level+1, "")
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}

				// We receive exactly a single table for a foreign key
				col.foreignKeyTable = &tbll[0]
			} else if col.ColumnTag.PointedKeyReference != "" && s.isArrayToTableStruct(field.Type) {
				tbll, err := s.parseField(field.Type.Elem(), level+1, "")
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}

				// We receive exactly a single table for a foreign key
				col.foreignKeyTable = &tbll[0]
			}

			// Add column
			tbl.columns = append(tbl.columns, col)
		}

		return []table{tbl}, nil

	} else if level == 0 {
		// For level 0 we search also for "embedded structs"
		for i := 0; i < val.NumField(); i++ {
			field := val.Field(i)

			if s.isTableStruct(field.Type) {
				tbll, err := s.parseField(field.Type.Elem(), level+1, field.Name)
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}
				tbl = append(tbl, tbll...)
			}
		}
	}

	return
}

// isFieldIgnored checks weather this field should be ignored
func (s ColumnSelector) isFieldIgnored(tbl *table, col *column) bool {
	// Always return primary keys
	if s.includePrimaryKeys && col.IsPrimaryKey {
		return false
	}

	// Get tag identifier we are looking for
	fieldIdentifier := structt.GetFieldName(col.Name) + "|" + getColumnIdentifier(tbl, col)

	// If we have a positive selection of fields, ignore all other fields
	if len(s.IncludeColumns) != 0 {
		include := false
		for _, f := range s.IncludeColumns {
			if fieldIdentifier == f {
				include = true
				break
			}
		}

		if !include {
			return true
		}
	}

	for _, f := range s.ExcludeColumns {
		if f == fieldIdentifier {
			return true
		}
	}

	return false
}

// isTableStruct checks weather val is a pointer to a struct
// that contains a DbMetadata field and is therefore referenced
// as a "table" struct
func (s ColumnSelector) isTableStruct(val reflect.Type) bool {

	// Pointer to a struct required
	if err := isPointerType(val, reflect.Struct); err != nil {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.Elem().FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// isArrayToTableStruct checks weather val is an array to a struct
// type that contains a DbMetadata field
func (s ColumnSelector) isArrayToTableStruct(val reflect.Type) bool {
	if val.Kind() != reflect.Slice {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.Elem().FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// Wehre returns a new selection condition for the query.
// All single where statements are concatenated by a logical AND
func (q *Query) Where() *Where {
	return &Where{
		query: q,
	}
}

// Column sets the expression for the provided database column.
//
// The column can either be a raw column name in format table.column
// without a "|", or a const expression generated by go-ddl.
//
// The operator has to be a valid sql operator like "=", ">", "<", ...
func (w *Where) Column(columnName, operator string, value any) *Where {
	if strings.Count(columnName, "|") == 1 {
		// Const expression provided
		pipe := strings.Index(columnName, "|")
		w.column = columnName[pipe+1:]
	} else {
		w.column = columnName
	}

	// Set values
	w.operator = operator
	w.val = value

	return w
}

// IgnoreCase sets wweather the case of a string column
// should be ignored.
//
// The query will error if the column or value are not a
// string
func (w *Where) IgnoreCase(ignore bool) *Where {
	w.ignoreCase = true
	return w
}

// Add adds this where statemen to the query
func (w *Where) Add() *Query {
	if w.column == "" {
		return w.query
	}

	if w.ignoreCase {
		w.query.whereStatement += fmt.Sprintf("\tAND LOWER(%s) %s LOWER(?)\n", w.column, w.operator)
	} else {
		w.query.whereStatement += fmt.Sprintf("\tAND %s %s ?\n", w.column, w.operator)
	}

	w.query.wherePlaceholder = append(w.query.wherePlaceholder, w.val)

	return w.query
}

// IfNotZero adds this expression to the query if "value" is not zero.
// Only generic go types like string or int are supported
func (w *Where) IfNotZero() *Query {
	if !isZero(w.val) {
		w.Add()
	}

	return w.query
}

// Run executes the query and fetches the data from the database
// into *dst.
//
// Any error that occured druing building the query or while fetching
// the data is returned here
func (q *Query) Run() DatabaseError {
	if q.err != nil {
		return q.err
	}

	// Apply default selector values
	if !q.customSelector {
		q.columnSelector.ForeignKeyReference = true
	}

	// Parse all struct fields
	tbls, err := q.columnSelector.parseField(q.typ, 0, "")
	if err != nil {
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to parse fields of struct %q: %s", q.typ, err),
			Response: errors.InternalError(),
		}
	}

	// Get select statement to execute (use a dummy struct to not initialize fields)
	dummy := reflect.New(q.typ)
	sel := "SELECT\n"
	var join, from, orderBy string
	for i, t := range tbls {
		// reflect.New creates a pointer
		writeTo := dummy.Elem()
		if t.fieldName != "" {
			writeTo = writeTo.FieldByName(t.fieldName).Elem()
		}
		selAdd, joinAdd, _ := q.getColumns(t, writeTo)
		if q.err != nil {
			return q.err
		}

		// Initialize from statement
		if i == 0 {
			from = getTableIdentifier(&t)
		} else if from != getTableIdentifier(&t) {
			join = "JOIN " + getTableIdentifier(&t)
		}

		// Append select data
		sel += selAdd
		join += joinAdd

		// Order by PrimaryKeys
		for _, c := range t.columns {
			if c.IsPrimaryKey {
				if orderBy == "" {
					orderBy = getColumnIdentifier(&t, &c)
				} else {
					orderBy += ", " + getColumnIdentifier(&t, &c)
				}
			}
		}
	}
	if orderBy != "" {
		orderBy = "\nORDER BY " + orderBy
	}
	if q.whereStatement != "" {
		q.whereStatement = "\n" + q.whereStatement
	}

	// Execute the statement
	fullSelect := fmt.Sprintf("%s\t1\nFROM %s\n%sWHERE 1=1%s%s", sel, from, join, q.whereStatement, orderBy)
	rows, err := q.operator.dbUtils.Db.Query(fullSelect, q.wherePlaceholder...)
	if err != nil {
		logger.Debug("Select for failed query:\n%s", fullSelect)
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to query value: %s", err),
			Response: errors.InternalError(),
		}
	}
	defer rows.Close()

	// Expect a single value
	var tmp any
	if !q.isArray && rows.Next() {
		var columns []any
		for _, t := range tbls {
			_, _, mappedAdd := q.getColumns(t, q.dst.Elem())
			columns = append(columns, mappedAdd...)
		}
		columns = append(columns, &tmp)

		// Scan the data into the struct
		if err := rows.Scan(columns...); err != nil {
			logger.Error("Query error for db: %s", err)
			return databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to scan row: %s", err),
				Response: errors.InternalError(),
			}
		}
	} else if !q.isArray {
		return databaseErr{
			Typ:      NoRows,
			Err:      fmt.Errorf("no data found in select"),
			Response: errors.NewError("No data found", 404),
		}
	}
	// Are there any remaining rows?
	if !q.isArray && rows.Next() {
		// Get the count of them for debug purporses
		counter := 2
		for rows.Next() {
			counter++
		}

		return databaseErr{
			Typ:      TooManyRows,
			Err:      fmt.Errorf("found %d rows instead of a single one", counter),
			Response: errors.NewError("Too many data found", 409),
		}
	}

	// Multiple values
	for rows.Next() {
		dst := reflect.New(q.typ)
		var columns []any
		for _, t := range tbls {
			_, _, mappedAdd := q.getColumns(t, dst.Elem())
			columns = append(columns, mappedAdd...)
		}
		columns = append(columns, &tmp)

		// Scan elements
		if err := rows.Scan(columns...); err != nil {
			logger.Error("Query error for db: %s", err)
			return databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to scan row: %s", err),
				Response: errors.InternalError(),
			}
		} else {
			q.dst.Set(reflect.Append(q.dst, dst.Elem()))
		}
	}

	// Include n:1 relationships
	if q.columnSelector.PointedKeyReference && (!q.isArray || q.dst.Len() > 0) {

		// Find all fields with a pointed key reference
		for _, t := range tbls {

			// We need to execute it for every row.
			// @TODO make this concurrent :)
			var subError error
			if q.isArray {
				for i := 0; i < q.dst.Len(); i++ {
					if t.fieldName != "" {
						// Query embedded
						subError = q.findAllPointedReferences(t, q.dst.Index(i).FieldByName(t.fieldName).Addr())
					} else {
						subError = q.findAllPointedReferences(t, q.dst.Index(i).Addr())
					}

					if subError != nil {
						break
					}
				}
			} else {
				if t.fieldName != "" {
					// Query embedded
					subError = q.findAllPointedReferences(t, q.dst.FieldByName(t.fieldName))
				} else {
					subError = q.findAllPointedReferences(t, q.dst)
				}
			}

			if subError != nil {
				return databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("failed to scan pointed key reference: %s", subError),
					Response: errors.InternalError(),
				}
			}

		}
	}

	return nil
}

// findAllPointedReferences queries struct fields with a tag "PointedForeignKey"
// to resolve n:1 relationships and queries the data from the db.
// Val is expected to be a *struct represented by table
func (q *Query) findAllPointedReferences(t table, val reflect.Value) error {

	// Loop through all fields and find pointed key refernces
	for _, c := range t.columns {
		if c.PointedKeyReference == "" {
			// Nothing found
			continue
		}

		// Find field
		col := column{}
		for _, cc := range c.foreignKeyTable.columns {
			if getColumnIdentifier(c.foreignKeyTable, &cc) == c.PointedKeyReference {
				col = cc
				break
			}
		}
		if col.fieldName == "" || col.ForeignKeyReference == "" {
			return fmt.Errorf("no referenced field found for %q in %q", c.PointedKeyReference, c.foreignKeyTable.typ)
		}

		// Extract the field name to which the foreign key points to
		fieldName := col.ForeignKeyReference
		lastPoint := strings.Index(fieldName, ".")
		fieldName = structt.GetFieldName(fieldName[lastPoint+1:])

		// Copy this query struct to apply customizations
		field := val.Elem().Field(c.position)
		identValue := val.Elem().FieldByName(fieldName)
		qCopy := *q
		qCopy.isArray = true
		qCopy.wherePlaceholder = []any{identValue.Interface()}
		qCopy.whereStatement = fmt.Sprintf("\tAND %s = ?", getColumnIdentifier(c.foreignKeyTable, &col))
		qCopy.typ = field.Type().Elem()
		qCopy.dst = field.Addr().Elem()

		// Query it!
		return qCopy.Run()
	}

	return nil

}

// getColumns returns a list of columns (comma and \n seperated)
// of the provided table.
//
// Any join statement that is needed to select
// these columns will be added.
//
// Because the mechanism of creating a select statement and mapping
// the column values to a struct is the same, this function initializes
// an array of pointers that are pointing to the matching
// fields of dst
func (q *Query) getColumns(tbl table, dst reflect.Value) (sel string, join string, mapped []any) {
	if q.err != nil {
		return
	}

	for _, c := range tbl.columns {
		if c.PointedKeyReference != "" {
			// We select this value later (array of []struct)
		} else if c.ForeignKeyReference != "" && c.isForeignKeyReference {

			// 1:1 relationship => we expect a pointer to a struct
			field := dst.Field(c.position)
			if field.Type().Kind() != reflect.Pointer || field.Type().Elem().Kind() != reflect.Struct {
				q.err = databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("expected a pointer to a struct for table type %s.%s", tbl.Table, c.Name),
					Response: errors.InternalError(),
				}
				return
			}

			// The pointer can be nil -> initialize a new struct
			var structVal reflect.Value
			if field.IsNil() {
				structVal = reflect.New(field.Type().Elem())
				// Set field to pointer
				field.Set(structVal)
				structVal = structVal.Elem()
			} else {
				structVal = field.Elem()
			}

			if q.columnSelector.ForeignKeyReference {
				lastDot := strings.LastIndex(c.ForeignKeyReference, ".")
				referencedTable := c.ForeignKeyReference[0:lastDot]
				join += fmt.Sprintf("LEFT JOIN %s ON %s = %s\n", referencedTable, c.ForeignKeyReference, getColumnIdentifier(&tbl, &c))

				refTableName := referencedTable
				refTableSchema := ""
				lastDotTwo := strings.LastIndex(referencedTable, ".")
				if lastDotTwo != -1 {
					refTableSchema = referencedTable[0:lastDotTwo]
					refTableName = referencedTable[lastDotTwo:]
				}
				tbl := table{
					MetadataTag: structt.MetadataTag{
						Schema: refTableSchema,
						Table:  refTableName,
					},
					typ:     structVal.Type(),
					columns: c.foreignKeyTable.columns,
				}
				addSel, addJoin, addMapped := q.getColumns(tbl, structVal)
				sel += addSel
				join += addJoin
				mapped = append(mapped, addMapped...)
			} else {
				// Include only the ID of the struct in select and reference
				// the struct ID
				sel += "\t" + getColumnIdentifier(&tbl, &c) + ",\n"

				// Find the position of the referenced column in the struct
				lastDot := strings.LastIndex(c.ForeignKeyReference, ".")
				referencedColumn := c.ForeignKeyReference[lastDot+1:]
				position := -1
				for _, cc := range c.foreignKeyTable.columns {
					if cc.Name == referencedColumn {
						position = cc.position
					}
				}

				// Referenced field not found
				if position == -1 {
					q.err = databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("didn't found referenced column %q in %s", referencedColumn, structVal.Type()),
						Response: errors.InternalError(),
					}
					return
				}

				// Get the pointer to the referenced column
				mapped = append(mapped, structVal.Field(position).Addr().Interface())
			}
		} else {
			// Simple select field
			sel += "\t" + getColumnIdentifier(&tbl, &c) + ",\n"
			mapped = append(mapped, dst.Field(c.position).Addr().Interface())
		}
	}

	return
}

// getColumnName returns the full reference of a column
// (schema.table.column)
func getColumnIdentifier(tbl *table, col *column) string {
	identifier := tbl.MetadataTag.Table + "." + col.Name
	if tbl.MetadataTag.Schema != "" {
		identifier = tbl.MetadataTag.Schema + "." + identifier
	}

	return identifier
}

// getTableIdentifier returns the full reference of a table
// (schema.table)
func getTableIdentifier(tbl *table) string {
	rtc := tbl.Table
	if tbl.Schema != "" {
		rtc = tbl.Schema + "." + tbl.Table
	}

	return rtc
}

// Insert statement in a database context
type Insert struct {

	// Internal reference to an operator
	operator *StructOperator

	// Fields to exclude to query
	columnSelector ColumnSelector

	// Weather the selector was set
	customSelector bool

	// Type of the struct to insert
	typ reflect.Type

	// Value to insert (slice of types)
	insertVal reflect.Value

	// The last occured error will be stored in this fild and is
	// only returned in "Run()".
	// If any error occured, the (internal) processing is stopped
	err DatabaseError
}

// Insert will insert a single struct into the table defined within metadata.
// A pointer to a struct is expected (*struct).
// Embedded structs are not supported!
func (o *StructOperator) Insert(val any) *Insert {
	rtc := &Insert{
		operator: o,
	}

	// Check for pointer
	if !rtc.columnSelector.isTableStruct(reflect.TypeOf(val)) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to a table struct: %s", reflect.TypeOf(val)),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = reflect.TypeOf(val).Elem()
	rtc.insertVal = reflect.MakeSlice(reflect.SliceOf(rtc.typ), 0, 0)
	rtc.insertVal = reflect.Append(rtc.insertVal, reflect.ValueOf(val).Elem())

	return rtc
}

// Insert will insert a list of structs into the table defined within metadata.
// A pointer to a an array is expected (*[]struct).
// Embedded structs are not supported!
func (o *StructOperator) InsertSlice(val any) *Insert {
	rtc := &Insert{
		operator: o,
	}

	// Check for pointer
	t := reflect.TypeOf(val)
	if isPointerType(t, reflect.Slice) != nil || !rtc.columnSelector.isArrayToTableStruct(t.Elem()) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to an array of table structs: %s", t),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = t.Elem().Elem()
	rtc.insertVal = reflect.ValueOf(val).Elem()

	return rtc
}

// Selector sets a custom selector for columns which should be inserted
func (q *Insert) Selector(selector ColumnSelector) *Insert {
	q.columnSelector = selector
	q.customSelector = true
	q.columnSelector.ForeignKeyReference = false
	return q
}

// Run executes the insert operation and returns all errors
// with the first inserted ID for an auto_increment column
func (q *Insert) Run() (int64, error) {
	if q.err != nil {
		return 0, q.err
	}

	// Parse all fields. We expect a single table (level != 0)
	tbls, err := q.columnSelector.parseField(q.typ, 1, "")
	if err != nil {
		return 0, err
	}
	if len(tbls) < 1 {
		return 0, fmt.Errorf("no table received form parsing struct")
	}

	// Nothing to insert
	if q.insertVal.Len() == 0 {
		logger.Debug("Got no data to insert for table %q", getTableIdentifier(&tbls[0]))
		return 0, nil
	}

	// Build insert header
	insert := "INSERT INTO " + getTableIdentifier(&tbls[0]) + " (\n\t"
	ii := 0
	for _, c := range tbls[0].columns {
		// Skip non insertable values. If we have only one column, it's the users fault!
		if c.AutoIncrement || c.PointedKeyReference != "" {
			continue
		}

		if ii != 0 {
			insert += ", "
		}
		insert += getColumnIdentifier(&tbls[0], &c)
		ii = ii + 1
	}
	insert += "\n) VALUES"

	// Build insert data
	placeholders := make([]any, 0)
	for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
		ii = 0
		for colI, col := range tbls[0].columns {
			// Insert syntax preperatiosn
			if colI == 0 {
				if rowI != 0 {
					insert += ","
				}
				insert += "\n\t("
			}

			// Skip auto increment. If we have only one column, it's the users fault!
			if col.AutoIncrement || col.PointedKeyReference != "" {
				continue
			}
			if ii != 0 {
				insert += ", "
			}

			// Value to insert
			value := q.insertVal.Index(rowI).Field(col.position).Interface()

			// If we have a 1:1 reference (which we don't create), the value to insert
			// has to be extracted from the referenced struct
			if col.isForeignKeyReference {
				// Get the referenced column position
				lastDot := strings.LastIndex(col.ForeignKeyReference, ".")
				referencedColumn := col.ForeignKeyReference[lastDot+1:]
				position := -1
				for _, cc := range col.foreignKeyTable.columns {
					if cc.Name == referencedColumn {
						position = cc.position
					}
				}

				// Referenced field not found
				if position == -1 {
					return 0, databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("didn't found referenced column %q in %s", referencedColumn, reflect.ValueOf(value).Type()),
						Response: errors.InternalError(),
					}
				}

				value = reflect.ValueOf(value).Field(position).Interface()
			}

			// We use a default value if the column is not nullable
			// and the user provided a "null" value (go-ddl only sets the field
			// to a sql.Null type if the column is not nullable)
			if col.HasDefaultValue && isZero(value) {
				insert += fmt.Sprintf("DEFAULT(%s)", getColumnIdentifier(&tbls[0], &col))
			} else {
				insert += "?"
				placeholders = append(placeholders, value)
			}

			ii = ii + 1
		}
		insert += ")"
	}

	// Execute the insert
	res, err := q.operator.dbUtils.Db.Exec(insert, placeholders...)
	if err != nil {
		logger.Debug("Statement for failed insert:\n%s", insert)
		return 0, err
	}

	// We will get the ID of the first inserted row (for MariaDB auto increment).
	// The ID of all other rows will ALWAYS be incremented by one (InnoDB)
	insId, _ := res.LastInsertId()
	insIdOrig := insId

	// Insert n:1 relationships
	for _, col := range tbls[0].columns {
		if col.PointedKeyReference == "" || col.foreignKeyTable == nil || !q.columnSelector.PointedKeyReference {
			continue
		}

		// Find the referenced field
		coll := column{}
		for _, cc := range col.foreignKeyTable.columns {
			if getColumnIdentifier(col.foreignKeyTable, &cc) == col.PointedKeyReference {
				coll = cc
				break
			}
		}
		if coll.fieldName == "" || coll.ForeignKeyReference == "" {
			return 0, fmt.Errorf("no referenced field found for %q in %q", col.PointedKeyReference, col.foreignKeyTable.typ)
		}

		// Extract the field name to which the foreign key points to
		fieldName := coll.ForeignKeyReference
		lastPoint := strings.Index(fieldName, ".")
		fieldName = structt.GetFieldName(fieldName[lastPoint+1:])

		// Build array with data we need to insert
		insArray := reflect.MakeSlice(reflect.SliceOf(col.foreignKeyTable.typ), 0, 0)
		for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
			field := q.insertVal.Index(rowI).Field(col.position)

			// Get identifier of the row we need to set for the foreign key.
			// This HAS TO BE the primary key of the table -> use auto_increment
			// if last inserted ID it not zero
			identifier := q.insertVal.Index(rowI).FieldByName(fieldName)
			if insId != 0 {
				identifier = reflect.ValueOf(int(insId))
				insId++
			}

			// Set this identifier for every element
			for i := 0; i < field.Len(); i++ {
				sF := field.Index(i).FieldByName(coll.fieldName)
				sF.Set(identifier)
				insArray = reflect.Append(insArray, field.Index(i))
			}
		}

		// Copy this insert struct to apply customizations
		qCopy := *q
		qCopy.typ = insArray.Type().Elem()
		qCopy.insertVal = insArray
		_, errNew := qCopy.Run()
		if errNew != nil {
			return 0, databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to insert pointed key reference %s: %s", qCopy.typ, errNew),
				Response: errors.InternalError(),
			}
		}
	}

	return insIdOrig, err
}

// Update statement in a database context
type Update struct {

	// Internal reference to an operator
	operator *StructOperator

	// Fields to exclude to query
	columnSelector ColumnSelector

	// Weather the selector was set
	customSelector bool

	// Type of the struct to insert
	typ reflect.Type

	// Value to insert (slice of types)
	insertVal reflect.Value

	// The last occured error will be stored in this fild and is
	// only returned in "Run()".
	// If any error occured, the (internal) processing is stopped
	err DatabaseError
}

// Update will update a single row of the database.
// A pointer to a struct is expected (*struct).
// Embedded structs are not supported!
func (o *StructOperator) Update(val any) *Update {
	rtc := &Update{
		operator: o,
	}

	// Check for pointer
	if !rtc.columnSelector.isTableStruct(reflect.TypeOf(val)) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to a table struct: %s", reflect.TypeOf(val)),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = reflect.TypeOf(val).Elem()
	rtc.insertVal = reflect.MakeSlice(reflect.SliceOf(rtc.typ), 0, 0)
	rtc.insertVal = reflect.Append(rtc.insertVal, reflect.ValueOf(val).Elem())

	return rtc
}

// UpdateSlice will update a list of rows in the database.
// A pointer to a an array is expected (*[]struct).
// Embedded structs are not supported!
func (o *StructOperator) UpdateSlice(val any) *Update {
	rtc := &Update{
		operator: o,
	}

	// Check for pointer
	t := reflect.TypeOf(val)
	if isPointerType(t, reflect.Slice) != nil || !rtc.columnSelector.isArrayToTableStruct(t.Elem()) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to an array of table structs: %s", t),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = t.Elem().Elem()
	rtc.insertVal = reflect.ValueOf(val).Elem()

	return rtc
}

// Selector sets a custom selector for columns which should be inserted
func (q *Update) Selector(selector ColumnSelector) *Update {
	q.columnSelector = selector
	q.customSelector = true
	q.columnSelector.ForeignKeyReference = false
	return q
}

// Run executes the insert operation and returns all errors
func (q *Update) Run() error {
	if q.err != nil {
		return q.err
	}

	// A primary key is needed to identify the row to update
	q.columnSelector.includePrimaryKeys = true

	// Parse all fields. We expect a single table (level != 0)
	tbls, err := q.columnSelector.parseField(q.typ, 1, "")
	if err != nil {
		return err
	}
	if len(tbls) < 1 {
		return fmt.Errorf("no table received form parsing struct")
	}

	// Nothing to insert
	if q.insertVal.Len() == 0 {
		logger.Debug("Got no data to insert for table %q", getTableIdentifier(&tbls[0]))
		return nil
	}

	// We need expect exactly a primary key
	primKeys := 0
	primKeyJoin := ""
	for _, c := range tbls[0].columns {
		if c.IsPrimaryKey {
			primKeys++
			primKeyJoin = fmt.Sprintf("ON vals.%s = tbl.%s", c.Name, c.Name)
		}
	}
	if primKeys != 1 {
		return fmt.Errorf("expected to find exactly a single primary key. Found %d", primKeys)
	}

	// Build update statement with values
	update := "UPDATE " + getTableIdentifier(&tbls[0]) + " tbl \nJOIN ("
	placeholders := make([]any, 0)
	for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
		ii := 0
		for colI, col := range tbls[0].columns {
			// Syntax preperatiosn
			if colI == 0 {
				if rowI != 0 {
					update += "\n\tUNION ALL"
				}
				update += "\n\tSELECT "
			}

			// Skip pointed key reference
			if col.PointedKeyReference != "" {
				continue
			}

			if ii != 0 {
				update += ", "
			}

			// Value to insert
			value := q.insertVal.Index(rowI).Field(col.position).Interface()

			// If we have a 1:1 reference (which we don't create), the value to insert
			// has to be extracted from the referenced struct
			if col.isForeignKeyReference {
				// Get the referenced column position
				lastDot := strings.LastIndex(col.ForeignKeyReference, ".")
				referencedColumn := col.ForeignKeyReference[lastDot+1:]
				position := -1
				for _, cc := range col.foreignKeyTable.columns {
					if cc.Name == referencedColumn {
						position = cc.position
					}
				}

				// Referenced field not found
				if position == -1 {
					return databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("didn't found referenced column %q in %s", referencedColumn, reflect.ValueOf(value).Type()),
						Response: errors.InternalError(),
					}
				}

				value = reflect.ValueOf(value).Field(position).Interface()
			}

			// We use a default value if the column is not nullable
			// and the user provided a "null" value (go-ddl only sets the field
			// to a sql.Null type if the column is not nullable)
			if col.HasDefaultValue && isZero(value) {
				update += fmt.Sprintf("DEFAULT(%s) AS %q", getColumnIdentifier(&tbls[0], &col), col.Name)
			} else {
				update += fmt.Sprintf("? AS %q", col.Name)
				placeholders = append(placeholders, value)
			}

			ii = ii + 1
		}
	}

	// Add join and set statements
	update += "\n) vals " + primKeyJoin + "\n SET "
	ii := 0
	for _, c := range tbls[0].columns {
		if c.IsPrimaryKey || c.PointedKeyReference != "" {
			continue
		}

		// Add colon
		if ii != 0 {
			update += ", "
		}

		// Add set statement
		update += fmt.Sprintf("tbl.%s = vals.%s", c.Name, c.Name)

		ii++
	}

	// Execute the update
	_, err = q.operator.dbUtils.Db.Exec(update, placeholders...)
	if err != nil {
		logger.Debug("Statement for failed update:\n%s", update)
		return err
	}

	// @TODO Add n:1 relationsipt (Delete + Insert again)

	return err
}
