package database

import (
	"fmt"
	"reflect"
	"strings"
	"sync"

	"git.rpjosh.de/RPJosh/go-ddl-parser/structt"
	"git.rpjosh.de/RPJosh/go-logger"
	"git.rpjosh.de/RPJosh/workout/pkg/errors"
)

type OrderByOrder string

const (
	ASC  OrderByOrder = "ASC"
	DESC OrderByOrder = "DESC"
)

// StructOperator contains extended functions for "DatabaseUtils"
// to query, update or delete structs generated by "go-ddl-parser"
// or manually tagged structs
type StructOperator struct {
	// Internal reference to the DatabaseUtils
	dbUtils *DatabaseUtils
}

type Query struct {

	// Internal reference to an operator
	operator *StructOperator

	// The destination type is an array instead
	// of a single struct
	isArray bool

	// Destination to write the result to:
	//  - Single value: pointer to a struct (*struct)
	//  - Multiple values: array of structs ([]struct)
	dst reflect.Value

	// Type of the struct to write the data to (single + multiple)
	typ reflect.Type

	// The last occured error will be stored in this fild and is
	// only returned in "Run()".
	// If any error occured, the (internal) processing is stopped
	err DatabaseError

	// Fields to exclude to query
	columnSelector ColumnSelector

	// Whether the selector was set
	customSelector bool

	// Custom columns to add to the query.
	// The name of a column is used as an index.
	// The value is the matching select value
	customColumns map[string]map[string]string

	// Custom where statement
	whereStatement string
	// Placeholders for the where statement
	wherePlaceholder []any

	// Order by statements set by user indexed by the table name in UPPER_CASE.
	// An empty string is specified for the root
	orderBy map[string]string

	// Custom order by statement
	customOrderBy             string
	customOrderByPlaceholders []any

	// Internal number of rows in a count query
	count int

	// Name of the sub table queried for n:1 relationships
	subTable string

	// Custom JOIN statement to append
	customJoin            string
	customJoinPlaceholder []any
}

// ColumnSelector specifies which columns should be selected or updated
type ColumnSelector struct {

	// Only include the specified columns.
	// The value should be a const expressiong generated by go-ddl
	IncludeColumns []string

	// Columns to exclude
	ExcludeColumns []string

	// Whether to include foreignKeyReferences (1:1 relationships).
	//   - Select: enabled by default
	//   - Insert: Ignored even if this value is "true"
	//   - Update: Ignored even if this value is "true"
	ForeignKeyReference bool

	// Whether to include columns that references this row
	// (n:1 relationships)
	PointedKeyReference bool

	// By default all pointed key references are fetched in a single select and
	// are mapped back by their value.
	// When setting this option, a select for every struct is executed asynchroniously.
	//
	// This option is recommended if the resulting size would be > 50.000 data points
	PointedKeyReferenceAsync bool

	// Whether primary keys should always be parsed
	includePrimaryKeys bool
}

// Where contains data for a specific where statement
type Where struct {

	// Internal reference to the query
	query *Query

	// Operator like "=", ">", "<", ...
	operator string

	// Column name to select
	column string

	// Value to insert as a placeholder
	val any

	// Ignore the case
	ignoreCase bool

	// Custom where statement to append to the query
	customWhere string
	// Custom values to append to the query
	customValue []any
}

type table struct {

	// Generic table information
	structt.MetadataTag

	// Type of this struct
	typ reflect.Type

	// Columns of this table
	columns []column

	// Only for level zero and multiple (embedded) tables
	fieldName string

	// The reflect.Value of the root, embedded value
	rootRef reflect.Value
}

type column struct {

	// Generic column information
	structt.ColumnTag

	// Position of the field within struct type
	position int

	// Table that is referenced by this column. It's filled when:
	//   - isForeignKeyReference = treu
	//   - [structt.ColumnTag.PointedKeyReference != ""]
	foreignKeyTable *table

	// Whether this field points to another struct that
	// is referenced via a foreign key.
	// We need this additional field besides [structt.ColumnTag.ForeignKeyReference] to
	// check if the go ddl-parser actually used a full struct instead
	// of only the primary key from the referenced table
	isForeignKeyReference bool

	// Name of the struct field the column is assigned to
	fieldName string
}

// Query analyzes the provided struct and selects all fields tagged
// with "dbColumn" from one or multiple tables and writes the result
// into *dst.
// If *dst is a nil pointer, the underlaying value to which the pointer points
// to will be initialized
//
// Exactly a single row is expected to be returned from the database.
func (d *StructOperator) Query(dst any) *Query {
	rtc := &Query{
		operator:      d,
		customColumns: map[string]map[string]string{},
		orderBy:       map[string]string{},
	}

	// Validate given type
	dstVal := reflect.ValueOf(dst)
	if err := isPointer(dstVal, reflect.Struct); err != nil {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for dst given: %s", err),
			Response: errors.InternalError(),
		}
	}
	rtc.dst = dstVal
	rtc.typ = reflect.TypeOf(dst).Elem()

	return rtc
}

// QuerySlice is like [Query] but writes multiple rows from the database
// to an array (*[]dst).
func (d *StructOperator) QuerySlice(dst any) *Query {
	rtc := &Query{
		isArray:       true,
		operator:      d,
		customColumns: map[string]map[string]string{},
		orderBy:       map[string]string{},
	}

	// Make sure that we got a slice
	dstType := reflect.TypeOf(dst)
	if dstType.Kind() != reflect.Pointer || dstType.Elem().Kind() != reflect.Slice || dstType.Elem().Elem().Kind() != reflect.Struct {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("expected a pointer to a slice containing structs for dst"),
			Response: errors.InternalError(),
		}
		return rtc
	}
	rtc.dst = reflect.ValueOf(dst).Elem()
	rtc.typ = dstType.Elem().Elem()

	return rtc
}

// Selector adds a column selector for the query
func (q *Query) Selector(selector ColumnSelector) *Query {
	q.columnSelector = selector
	q.customSelector = true
	return q
}

// parseField parses all fields of the provided struct{}.
// For a level != 0 this function always returns a single table
func (s ColumnSelector) parseField(val reflect.Type, level int, structField string) (tbl []table, e error) {

	// Table structs are identified by the metadata field.
	// Because we also get embedded fields in [FieldByName()], we check the index path
	if f, found := val.FieldByName(structt.MetadataFieldName); found && len(f.Index) == 1 {
		valTag, ok := f.Tag.Lookup(structt.MetadataTagId)
		if !ok {
			e = fmt.Errorf("no tag found for metadata in %s", val)
			return
		}

		// Tbl metadata
		tbl := table{
			MetadataTag: *structt.FromMetadataTag(valTag),
			typ:         val,
			fieldName:   structField,
		}

		for i := 0; i < val.NumField(); i++ {
			field := val.Field(i)

			// Get tag
			valTag, ok := field.Tag.Lookup(structt.ColumnTagId)
			if !ok {
				continue
			}

			col := column{
				ColumnTag: *structt.FromColumnTag(valTag),
				position:  i,
				fieldName: field.Name,
			}

			// Check if column is ignored
			if s.isFieldIgnored(&tbl, &col) {
				continue
			}

			// Set any foreign key reference
			if col.ColumnTag.ForeignKeyReference != "" && s.isTableStruct(field.Type) {
				col.isForeignKeyReference = col.ColumnTag.ForeignKeyReference != ""
				tbll, err := s.parseField(field.Type.Elem(), level+1, "")
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}

				// We receive exactly a single table for a foreign key
				col.foreignKeyTable = &tbll[0]
			} else if col.ColumnTag.PointedKeyReference != "" && s.isArrayToTableStruct(field.Type) {
				tbll, err := s.parseField(field.Type.Elem(), level+1, "")
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}

				// We receive exactly a single table for a foreign key
				col.foreignKeyTable = &tbll[0]
			}

			// Add column
			tbl.columns = append(tbl.columns, col)
		}

		return []table{tbl}, nil

	} else if level == 0 {
		// For level 0 we search also for "embedded structs"
		for i := 0; i < val.NumField(); i++ {
			field := val.Field(i)

			if s.isEmbeddedTableStruct(field.Type) {
				tbll, err := s.parseField(field.Type, level+1, field.Name)
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}
				tbl = append(tbl, tbll...)
			}
		}
	}

	return
}

// isFieldIgnored checks whether this field should be ignored
func (s ColumnSelector) isFieldIgnored(tbl *table, col *column) bool {
	// Always return primary keys
	if s.includePrimaryKeys && col.IsPrimaryKey {
		return false
	}

	// Get tag identifier we are looking for
	fieldIdentifier := structt.GetFieldName(col.Name) + "|" + getColumnIdentifier(tbl, col)

	// If we have a positive selection of fields, ignore all other fields
	if len(s.IncludeColumns) != 0 {
		include := false
		for _, f := range s.IncludeColumns {
			if fieldIdentifier == f {
				include = true
				break
			}

			// Check if wildcard matches
			if f == "*|"+tbl.Schema+"."+tbl.Table || f == "*|"+tbl.Table {
				include = true
				break
			}

			// We always include this field if it's a 1:n relationship and was included in
			// columns to include
			if col.PointedKeyReference != "" {
				lastDot := strings.LastIndex(col.PointedKeyReference, ".")
				pTable := col.PointedKeyReference[:lastDot]
				pColumn := col.PointedKeyReference[lastDot+1:]

				// Get directly
				//pDirect := col.fieldName + "|#" + pTable + "." + structt.GetFieldName(pColumn)
				pDirect := col.fieldName + "|#" + getColumnIdentifier(tbl, col) + col.fieldName
				if f == pDirect {
					include = true
					break
				}

				// Get by referenced sub id
				pIndirect := structt.GetFieldName(pColumn) + "|" + col.PointedKeyReference
				if f == pIndirect || strings.HasSuffix(f, "|"+pTable) {
					include = true
					break
				}
			}
		}

		if !include {
			return true
		}
	}

	for _, f := range s.ExcludeColumns {
		if f == fieldIdentifier {
			return true
		}

		// Check if wildcard matches
		if f == "*|"+tbl.Schema+"."+tbl.Table || f == "*|"+tbl.Table {
			return true
		}
	}

	return false
}

// isTableStruct checks weather val is a pointer to a struct
// that contains a DbMetadata field and is therefore referenced
// as a "table" struct
func (s ColumnSelector) isTableStruct(val reflect.Type) bool {

	// Pointer to a struct required
	if err := isPointerType(val, reflect.Struct); err != nil {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.Elem().FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// isTableStruct checks weather val is a struct
// that contains a DbMetadata field and is therefore referenced
// as a "table" struct
func (s ColumnSelector) isEmbeddedTableStruct(val reflect.Type) bool {

	// Struct type required
	if val.Kind() != reflect.Struct {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// isArrayToTableStruct checks weather val is an array to a struct
// type that contains a DbMetadata field
func (s ColumnSelector) isArrayToTableStruct(val reflect.Type) bool {
	if val.Kind() != reflect.Slice {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.Elem().FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// Wehre returns a new selection condition for the query.
// All single where statements are concatenated by a logical AND
func (q *Query) Where() *Where {
	return &Where{
		query: q,
	}
}

// Column sets the expression for the provided database column.
//
// The column can either be a raw column name in format table.column
// without a "|", or a const expression generated by go-ddl.
//
// The operator has to be a valid sql operator like "=", ">", "<", IN ...
func (w *Where) Column(columnName, operator string, value any) *Where {
	if strings.Count(columnName, "|") == 1 {
		// Const's expression provided
		pipe := strings.Index(columnName, "|")
		w.column = columnName[pipe+1:]
	} else {
		w.column = columnName
	}

	// Set values
	w.operator = operator
	w.val = value

	return w
}

// IgnoreCase sets whether the case of a string column
// should be ignored.
//
// The query will error if the column or value are not a
// string
func (w *Where) IgnoreCase(ignore bool) *Where {
	w.ignoreCase = true
	return w
}

// Add adds this where statemen to the query
func (w *Where) Add() *Query {

	// Process custom where statement
	if w.customWhere != "" {
		w.query.whereStatement += "\tAND (" + w.customWhere + "\n) "
		w.query.wherePlaceholder = append(w.query.wherePlaceholder, w.customValue...)

		return w.query
	} else if w.column == "" {
		return w.query
	}

	// Parse custom statement
	w.operator = strings.ToUpper(w.operator)
	switch w.operator {
	case "IN", "NOT IN":
		refVal := reflect.ValueOf(w.val)

		// Validate type
		if refVal.Type().Kind() != reflect.Slice {
			w.query.err = databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("expected an array for 'IN' / 'NOT IN' statement. Got type %s", refVal.Type().Kind()),
				Response: errors.InternalError(),
			}
			return w.query
		}

		// Loop through every field
		w.query.whereStatement += fmt.Sprintf("\tAND %s %s (", w.column, w.operator)
		for i := 0; i < refVal.Len(); i++ {
			if i != 0 {
				w.query.whereStatement += ", "
			}

			if w.ignoreCase {
				w.query.whereStatement += "LOWER(?)"
			} else {
				w.query.whereStatement += "?"
			}

			w.query.wherePlaceholder = append(w.query.wherePlaceholder, refVal.Index(i).Interface())
		}
		w.query.whereStatement += ")\n"
		return w.query
	}

	// Default processing
	if w.ignoreCase {
		w.query.whereStatement += fmt.Sprintf("\tAND LOWER(%s) %s LOWER(?)\n", w.column, w.operator)
	} else {
		w.query.whereStatement += fmt.Sprintf("\tAND %s %s ?\n", w.column, w.operator)
	}

	w.query.wherePlaceholder = append(w.query.wherePlaceholder, w.val)

	return w.query
}

// Custom adds a custom WHERE condition to the statment.
// You mustn't use this together with [Column()].
func (w *Where) Custom(statement string, values ...any) *Where {
	w.customWhere = statement
	w.customValue = values

	return w
}

// IfNotZero adds this expression to the query if "value" and "operator" is not zero.
// Only generic go types like string or int are supported
func (w *Where) IfNotZero() *Query {
	if !w.isZero(w.val) && w.operator != "" {
		w.Add()
	}

	return w.query
}

// IfAllNotZero adds this expression if all provided values are
// NOT zero. Only generic go types are supported
func (w *Where) IfAllNotZero(vals ...any) *Query {
	for _, val := range vals {
		if w.isZero(val) {
			return w.query
		}
	}

	w.Add()
	return w.query
}

// isZero returns weather the provided value contains
// a default value for it's type
func (w *Where) isZero(val any) bool {
	refVal := reflect.ValueOf(val)

	// Default go type zero check
	if refVal.IsZero() {
		return true
	}

	// Array length > 0
	if (refVal.Kind() == reflect.Slice || refVal.Kind() == reflect.Array) && refVal.Len() == 0 {
		return true
	}

	return false
}

// OrderBy adds a custom order by statment to the select query.
// The name of a column and the sort order is expected ("COL", "ASC", "COL2", "DESC").
//
// The first value identifies the table name to add to the order by statement (for 1:n relationships).
// Provide an empty string for the root table
func (q *Query) OrderBy(tableName string, vals ...string) *Query {
	tableName = strings.ToUpper(tableName)
	orderBy := q.orderBy[tableName]

	for i := 0; i < len(vals); i++ {

		// Extract column name
		columnName := vals[i]
		if strings.Count(columnName, "|") == 1 {
			pipe := strings.Index(columnName, "|")
			columnName = columnName[pipe+1:]
		}

		if i == len(vals)-1 {
			logger.Warning("No sort direction provided for column %q", columnName)
			break
		}

		// Add column to statement
		if orderBy != "" {
			orderBy += ", "
		}
		orderBy += columnName + " " + vals[i+1]
		i++
	}

	q.orderBy[tableName] = orderBy
	return q
}

// CustomOrderBy adds an custom order by statement to the query.
// It is appended to the "default" statements defined by [OrderBy]
func (q *Query) CustomOrderBy(statement string, placeholders ...any) *Query {
	q.customOrderBy = statement
	q.customOrderByPlaceholders = placeholders

	return q
}

// CustomColumn adds a custom column to select from the table.
//
// The first value identifies the table name to add this custom select for.
// Provide an empty string for the root table
func (q *Query) CustomColumn(tableName, fieldName, sel string) *Query {
	tableName = strings.ToUpper(tableName)
	selVal := q.customColumns[tableName]
	if selVal == nil {
		selVal = map[string]string{}
	}
	selVal[fieldName] = sel

	q.customColumns[tableName] = selVal
	return q
}

// CustomJoin appends the provided JOIN statement after the
// automatically generated ones
func (q *Query) CustomJoin(join string, placeholders ...any) *Query {
	q.customJoin = join
	q.customJoinPlaceholder = placeholders
	return q
}

// Count only counts the number of rows and doesn't
// write anything into [dst]
func (q *Query) Count() (int, DatabaseError) {
	err := q.run(true)
	return q.count, err
}

// Run executes the query and fetches the data from the database
// into *dst.
//
// Any error that occured druing building the query or while fetching
// the data is returned here
func (q *Query) Run() DatabaseError {
	return q.run(false)
}

func (q *Query) run(onlyCount bool) DatabaseError {
	if q.err != nil {
		return q.err
	}

	// Apply default selector values
	if !q.customSelector {
		q.columnSelector.ForeignKeyReference = true
	}

	// Parse all struct fields
	tbls, err := q.columnSelector.parseField(q.typ, 0, "")
	if err != nil {
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to parse fields of struct %q: %s", q.typ, err),
			Response: errors.InternalError(),
		}
	}

	// Get select statement to execute (use a dummy struct to not initialize fields)
	dummy := reflect.New(q.typ)
	sel := "SELECT\n"
	var join, from, orderBy string
	for i, t := range tbls {
		// reflect.New creates a pointer
		writeTo := dummy.Elem()
		var rootWriteTo reflect.Value
		if t.fieldName != "" {
			writeTo = writeTo.FieldByName(t.fieldName)
			if writeTo.Kind() == reflect.Pointer {
				writeTo = writeTo.Elem()
			}

			rootWriteTo = dummy.Elem()
		}
		selAdd, joinAdd, _ := q.getColumns(t, writeTo, &rootWriteTo)
		if q.err != nil {
			return q.err
		}

		// Initialize from statement
		if i == 0 {
			from = getTableIdentifier(&t)
		} else if from != getTableIdentifier(&t) {
			join = "JOIN " + getTableIdentifier(&t)
		}

		// Append select data
		sel += selAdd
		join += joinAdd

		// Order by PrimaryKeys
		for _, c := range t.columns {
			if c.IsPrimaryKey {
				if orderBy == "" {
					orderBy = getColumnIdentifier(&t, &c)
				} else {
					orderBy += ", " + getColumnIdentifier(&t, &c)
				}
			}
		}
	}

	// Add custom joins
	if q.customJoin != "" {
		join += "\n" + q.customJoin
		q.wherePlaceholder = append(q.customJoinPlaceholder, q.wherePlaceholder...)
	}

	// Get custom order by statement
	custOrderBy := q.orderBy[q.subTable]
	if custOrderBy != "" {
		orderBy = "\nORDER BY " + custOrderBy
	} else if orderBy != "" && q.customOrderBy == "" {
		orderBy = "\nORDER BY " + orderBy
	}
	if q.customOrderBy != "" {
		if len(orderBy) != 0 {
			orderBy += ", "
		} else {
			orderBy = "\nORDER BY "
		}
		orderBy += q.customOrderBy
		q.wherePlaceholder = append(q.wherePlaceholder, q.customOrderByPlaceholders...)
	}

	if q.whereStatement != "" {
		q.whereStatement = "\n" + q.whereStatement
	}

	// Only count number of rows
	if onlyCount {
		sel = "SELECT COUNT(*) "
	} else {
		// Always select at least a single value.
		// We also need this to close any comma
		sel += "\t1"
	}

	// Execute the statement
	fullSelect := fmt.Sprintf("%s\nFROM %s\n%sWHERE 1=1%s%s", sel, from, join, q.whereStatement, orderBy)
	rows, err := q.operator.dbUtils.Db.Query(fullSelect, q.wherePlaceholder...)
	if err != nil {
		logger.Debug("Select for failed query:\n%s", fullSelect)
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to query value: %s", err),
			Response: errors.InternalError(),
		}
	}
	defer rows.Close()

	// We always get a single result for count(*)
	if onlyCount {
		rows.Next()
		if err := rows.Scan(&q.count); err != nil {
			return databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to scan row: %s", err),
				Response: errors.InternalError(),
			}
		}

		return nil
	}

	// Expect a single value
	var tmp any
	if !q.isArray && rows.Next() {
		var columns []any
		for _, t := range tbls {

			// Get value to write to
			writeTo := q.dst.Elem()
			var rootWriteTo reflect.Value
			if t.fieldName != "" {
				writeTo = writeTo.FieldByName(t.fieldName)
				if writeTo.Kind() == reflect.Pointer {
					writeTo = writeTo.Elem()
				}

				rootWriteTo = q.dst.Elem()
			}

			_, _, mappedAdd := q.getColumns(t, writeTo, &rootWriteTo)
			columns = append(columns, mappedAdd...)
		}
		columns = append(columns, &tmp)

		// Scan the data into the struct
		if err := rows.Scan(columns...); err != nil {
			logger.Error("Query error for db: %s", err)
			return databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to scan row: %s", err),
				Response: errors.InternalError(),
			}
		}
	} else if !q.isArray {
		return databaseErr{
			Typ:      NoRows,
			Err:      fmt.Errorf("no data found in select"),
			Response: errors.NewError("No data found", 404),
		}
	}
	// Are there any remaining rows?
	if !q.isArray && rows.Next() {
		// Get the count of them for debug purporses
		counter := 2
		for rows.Next() {
			counter++
		}

		return databaseErr{
			Typ:      TooManyRows,
			Err:      fmt.Errorf("found %d rows instead of a single one", counter),
			Response: errors.NewError("Too many data found", 409),
		}
	}

	// Multiple values
	i := 0
	for rows.Next() {
		i++
		dst := reflect.New(q.typ)
		var columns []any
		for _, t := range tbls {

			// Get value to write to
			writeTo := dst.Elem()
			var rootWriteTo reflect.Value
			if t.fieldName != "" {
				writeTo = writeTo.FieldByName(t.fieldName)
				if writeTo.Kind() == reflect.Pointer {
					writeTo = writeTo.Elem()
				}

				rootWriteTo = dst.Elem()
			}
			_, _, mappedAdd := q.getColumns(t, writeTo, &rootWriteTo)
			columns = append(columns, mappedAdd...)
		}
		columns = append(columns, &tmp)

		// Scan elements
		if err := rows.Scan(columns...); err != nil {
			logger.Error("Query error for db: %s", err)
			return databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to scan row: %s", err),
				Response: errors.InternalError(),
			}
		} else {
			q.dst.Set(reflect.Append(q.dst, dst.Elem()))
		}

		// Limit max number of rows
		if i > 100000 {
			logger.Warning("Received maximum result size of 100.000 rows. Aborting")
			logger.Debug("Select statement:\n%s", fullSelect)
			rows.Close()
			break
		}
	}

	// Include n:1 relationships
	if q.columnSelector.PointedKeyReference && (!q.isArray || q.dst.Len() > 0) {

		// Find all fields with a pointed key reference
		for _, t := range tbls {
			var subError error
			if q.isArray {
				valArray := []reflect.Value{}
				useAllSelect := !q.columnSelector.PointedKeyReferenceAsync
				var wg sync.WaitGroup

				for i := 0; i < q.dst.Len(); i++ {
					var thisVal reflect.Value
					if t.fieldName != "" {
						// Query embedded
						thisVal = q.dst.Index(i).FieldByName(t.fieldName).Addr()
					} else {
						thisVal = q.dst.Index(i).Addr()
					}

					if useAllSelect {
						valArray = append(valArray, thisVal)
					} else {
						wg.Add(1)
						go func() {
							if err := q.findAllPointedReferences(t, []reflect.Value{thisVal}); err != nil {
								logger.Warning("Failed to select pointed key reference: %s", err)
							}
							wg.Done()
						}()
					}
				}
				wg.Wait()

				if useAllSelect {
					subError = q.findAllPointedReferences(t, valArray)
				}
			} else {
				valArray := []reflect.Value{}
				if t.fieldName != "" {
					// Query embedded
					valArray = append(valArray, q.dst.FieldByName(t.fieldName))
				} else {
					valArray = append(valArray, q.dst)
				}

				subError = q.findAllPointedReferences(t, valArray)
			}

			if subError != nil {
				return databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("failed to scan pointed key reference: %s", subError),
					Response: errors.InternalError(),
				}
			}
		}
	}

	return nil
}

// findAllPointedReferences queries struct fields with a tag "PointedForeignKey"
// to resolve n:1 relationships and queries the data from the db.
// Val is expected to be a *struct represented by table
func (q *Query) findAllPointedReferences(t table, values []reflect.Value) error {

	// Loop through all fields and find pointed key refernces
	for _, c := range t.columns {
		if c.PointedKeyReference == "" {
			// Nothing found
			continue
		}

		// Find field
		col := column{}
		for _, cc := range c.foreignKeyTable.columns {
			if getColumnIdentifier(c.foreignKeyTable, &cc) == c.PointedKeyReference {
				col = cc
				break
			}
		}
		if col.fieldName == "" || col.ForeignKeyReference == "" {
			// Suspress error if all fieds from the pointed table were ignored
			tableIdentifier1 := c.PointedKeyReference[0:strings.LastIndex(c.PointedKeyReference, ".")]
			tableIdentifier2 := tableIdentifier1
			if strings.Contains(tableIdentifier2, ".") {
				tableIdentifier2 = tableIdentifier2[strings.LastIndex(tableIdentifier2, ".")+1:]
			}
			for _, ex := range q.columnSelector.ExcludeColumns {
				if ex == "*|"+tableIdentifier1 || ex == "*|"+tableIdentifier2 {
					// logger.Trace("Ignoring pointed key reference for %q in %q. Found an matching ignore statement", c.PointedKeyReference, c.foreignKeyTable.typ)
					return nil
				}
			}

			return fmt.Errorf("no referenced field found for %q in %q", c.PointedKeyReference, c.foreignKeyTable.typ)
		}

		// Extract the field name to which the foreign key points to
		fieldName := col.ForeignKeyReference
		lastPoint := strings.LastIndex(fieldName, ".")
		fieldName = structt.GetFieldName(fieldName[lastPoint+1:])

		// Copy this query struct to apply customizations
		qCopy := *q
		qCopy.isArray = true
		qCopy.wherePlaceholder = []any{}
		qCopy.whereStatement = fmt.Sprintf("\tAND %s IN (", getColumnIdentifier(c.foreignKeyTable, &col))
		// Get the table name to fetch
		qCopy.subTable = strings.ToUpper(c.foreignKeyTable.Table)

		// Destination to write this value to
		for i, val := range values {
			field := val.Elem().Field(c.position)
			identValue := val.Elem().FieldByName(fieldName)

			// Initialize type
			if i == 0 {
				qCopy.typ = field.Type().Elem()
				// We use the first element as a buffer
				qCopy.dst = field.Addr().Elem()

			} else {
				qCopy.whereStatement += ", "
			}

			// Add to where statement
			qCopy.wherePlaceholder = append(qCopy.wherePlaceholder, identValue.Interface())
			qCopy.whereStatement += "?"
		}
		qCopy.whereStatement += ")"

		// Query it!
		if err := qCopy.Run(); err != nil {
			return err
		}

		// Map the array elements to the correct field again
		if len(values) != 1 {

			// Initialize holder values
			holders := make([]pointedReferenceHolder, len(values))
			for i, val := range values {
				field := val.Elem().Field(c.position)
				identValue := val.Elem().FieldByName(fieldName)

				holders[i] = pointedReferenceHolder{
					Field:      field,
					Identity:   identValue,
					FieldSlice: reflect.MakeSlice(field.Type(), 0, 0),
				}
			}

			// Loop through all values
			for i := 0; i < qCopy.dst.Len(); i++ {
				elValue := qCopy.dst.Index(i).FieldByName(col.fieldName)

				for o, val := range holders {
					if val.Identity.Equal(elValue) {
						holders[o].FieldSlice = reflect.Append(holders[o].FieldSlice, qCopy.dst.Index(i))
					}
				}
			}

			// Set fields
			for _, holder := range holders {
				holder.Field.Set(holder.FieldSlice)
			}
		}
	}

	return nil
}

// pointedReferenceHolder is a placeholder struct to store information
// for a specific 1:n field
type pointedReferenceHolder struct {
	// Field of the struct to set the array value to
	Field reflect.Value

	// Identity value
	Identity reflect.Value

	// Slice containing the temporary elements
	FieldSlice reflect.Value
}

// getColumns returns a list of columns (comma and \n seperated)
// of the provided table.
//
// Any join statement that is needed to select
// these columns will be added.
//
// Because the mechanism of creating a select statement and mapping
// the column values to a struct is the same, this function initializes
// an array of pointers that are pointing to the matching
// fields of dst
func (q *Query) getColumns(tbl table, dst reflect.Value, root *reflect.Value) (sel string, join string, mapped []any) {
	if q.err != nil {
		return
	}

	for _, c := range tbl.columns {
		if c.PointedKeyReference != "" {
			// We select this value later (array of []struct)
		} else if c.ForeignKeyReference != "" && c.isForeignKeyReference {

			// 1:1 relationship → we expect a pointer to a struct
			field := dst.Field(c.position)
			if field.Type().Kind() != reflect.Pointer || field.Type().Elem().Kind() != reflect.Struct {
				q.err = databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("expected a pointer to a struct for table type %s.%s", tbl.Table, c.Name),
					Response: errors.InternalError(),
				}
				return
			}

			// The pointer can be nil → initialize a new struct
			var structVal reflect.Value
			if field.IsNil() {
				structVal = reflect.New(field.Type().Elem())
				// Set field to pointer
				field.Set(structVal)
				structVal = structVal.Elem()
			} else {
				structVal = field.Elem()
			}

			if q.columnSelector.ForeignKeyReference {
				lastDot := strings.LastIndex(c.ForeignKeyReference, ".")
				referencedTable := c.ForeignKeyReference[0:lastDot]
				join += fmt.Sprintf("LEFT JOIN %s ON %s = %s\n", referencedTable, c.ForeignKeyReference, getColumnIdentifier(&tbl, &c))

				refTableName := referencedTable
				refTableSchema := ""
				lastDotTwo := strings.LastIndex(referencedTable, ".")
				if lastDotTwo != -1 {
					refTableSchema = referencedTable[0:lastDotTwo]
					refTableName = referencedTable[lastDotTwo+1:]
				}
				tbl := table{
					MetadataTag: structt.MetadataTag{
						Schema: refTableSchema,
						Table:  refTableName,
					},
					typ:     structVal.Type(),
					columns: c.foreignKeyTable.columns,
				}
				addSel, addJoin, addMapped := q.getColumns(tbl, structVal, nil)
				sel += addSel
				join += addJoin
				mapped = append(mapped, addMapped...)
			} else {
				// Include only the ID of the struct in select and reference
				// the struct ID
				sel += "\t" + getColumnIdentifier(&tbl, &c) + ",\n"

				// Find the position of the referenced column in the struct
				lastDot := strings.LastIndex(c.ForeignKeyReference, ".")
				referencedColumn := c.ForeignKeyReference[lastDot+1:]
				position := -1
				for _, cc := range c.foreignKeyTable.columns {
					if cc.Name == referencedColumn {
						position = cc.position
					}
				}

				// Referenced field not found
				if position == -1 {
					q.err = databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("didn't found referenced column %q in %s", referencedColumn, structVal.Type()),
						Response: errors.InternalError(),
					}
					return
				}

				// Get the pointer to the referenced column
				mapped = append(mapped, structVal.Field(position).Addr().Interface())
			}
		} else {
			// Simple select field
			sel += "\t" + getColumnIdentifier(&tbl, &c) + ",\n"
			mapped = append(mapped, dst.Field(c.position).Addr().Interface())
		}
	}

	// Add any custom columns
	if customMap, ok := q.customColumns[q.subTable]; ok {
		for fieldName, sellecto := range customMap {
			dstVal := dst

			_, found := dstVal.Type().FieldByName(fieldName)
			if !found {

				// If an embedded struct was used, we also try to fetch the value
				// of the embedded type
				err := databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("didn't found custom field %q in %q", fieldName, dst.Type().Name()),
					Response: errors.InternalError(),
				}

				if root != nil && root.IsValid() {
					if _, found := root.Type().FieldByName(fieldName); found {
						dstVal = *root
					} else {
						q.err = err
						return
					}

				} else {
					q.err = err
					return
				}
			}

			// Simple select field
			sel += "\t" + sellecto + ",\n"
			mapped = append(mapped, dstVal.FieldByName(fieldName).Addr().Interface())
		}
	}

	return
}

// getColumnName returns the full reference of a column
// (schema.table.column)
func getColumnIdentifier(tbl *table, col *column) string {
	identifier := tbl.MetadataTag.Table + "." + col.Name
	if tbl.MetadataTag.Schema != "" {
		identifier = tbl.MetadataTag.Schema + "." + identifier
	}

	return identifier
}

// getTableIdentifier returns the full reference of a table
// (schema.table)
func getTableIdentifier(tbl *table) string {
	rtc := tbl.Table
	if tbl.Schema != "" {
		rtc = tbl.Schema + "." + tbl.Table
	}

	return rtc
}

// Insert statement in a database context
type Insert struct {

	// Internal reference to an operator
	operator *StructOperator

	// Fields to exclude to query
	columnSelector ColumnSelector

	// Whether the selector was set
	customSelector bool

	// Type of the struct to insert
	typ reflect.Type

	// Value to insert (slice of types)
	insertVal reflect.Value

	// The last occured error will be stored in this fild and is
	// only returned in "Run()".
	// If any error occured, the (internal) processing is stopped
	err DatabaseError
}

// Insert will insert a single struct into the table defined within metadata.
// A pointer to a struct is expected (*struct).
// Embedded structs are not supported!
func (o *StructOperator) Insert(val any) *Insert {
	rtc := &Insert{
		operator: o,
	}

	// Check for pointer
	if !rtc.columnSelector.isTableStruct(reflect.TypeOf(val)) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to a table struct: %s", reflect.TypeOf(val)),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = reflect.TypeOf(val).Elem()
	rtc.insertVal = reflect.MakeSlice(reflect.SliceOf(rtc.typ), 0, 0)
	rtc.insertVal = reflect.Append(rtc.insertVal, reflect.ValueOf(val).Elem())

	return rtc
}

// Insert will insert a list of structs into the table defined within metadata.
// A pointer to an array is expected (*[]struct).
// Embedded structs are not supported!
func (o *StructOperator) InsertSlice(val any) *Insert {
	rtc := &Insert{
		operator: o,
	}

	// Check for pointer
	t := reflect.TypeOf(val)
	if isPointerType(t, reflect.Slice) != nil || !rtc.columnSelector.isArrayToTableStruct(t.Elem()) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to an array of table structs: %s", t),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = t.Elem().Elem()
	rtc.insertVal = reflect.ValueOf(val).Elem()

	return rtc
}

// insertSlice is a wrapper for [InsertSlice] that
// accepts a [reflect.Value] instead of an interface
func (o *StructOperator) insertSlice(val reflect.Value) *Insert {
	rtc := &Insert{
		operator: o,
	}

	rtc.typ = val.Type().Elem()
	rtc.insertVal = val

	return rtc
}

// Selector sets a custom selector for columns which should be inserted
func (q *Insert) Selector(selector ColumnSelector) *Insert {
	q.columnSelector = selector
	q.customSelector = true
	q.columnSelector.ForeignKeyReference = false
	return q
}

// Run executes the insert operation and returns all errors
// with the first inserted ID for an auto_increment column
func (q *Insert) Run() (int64, DatabaseError) {
	if q.err != nil {
		return 0, q.err
	}

	// Parse all fields. We expect a single table (level != 0)
	tbls, err := q.columnSelector.parseField(q.typ, 1, "")
	if err != nil {
		return 0, databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to parse fields of struct %q: %s", q.typ, err),
			Response: errors.InternalError(),
		}
	}
	if len(tbls) < 1 {
		return 0, databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("no table received form parsing struct"),
			Response: errors.InternalError(),
		}
	}

	// Nothing to insert
	if q.insertVal.Len() == 0 {
		logger.Debug("Got no data to insert for table %q", getTableIdentifier(&tbls[0]))
		return 0, nil
	}

	// Build insert header
	insert := "INSERT INTO " + getTableIdentifier(&tbls[0]) + " (\n\t"
	ii := 0
	for _, c := range tbls[0].columns {
		// Skip non-insertable values. If we have only one column, it's the users fault!
		if c.AutoIncrement || c.PointedKeyReference != "" {
			continue
		}

		if ii != 0 {
			insert += ", "
		}
		insert += getColumnIdentifier(&tbls[0], &c)
		ii = ii + 1
	}
	insert += "\n) VALUES"

	// Build insert data
	placeholders := make([]any, 0)
	for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
		ii = 0
		for colI, col := range tbls[0].columns {
			// Insert syntax preperatiosn
			if colI == 0 {
				if rowI != 0 {
					insert += ","
				}
				insert += "\n\t("
			}

			// Skip auto increment. If we have only one column, it's the users fault!
			if col.AutoIncrement || col.PointedKeyReference != "" {
				continue
			}
			if ii != 0 {
				insert += ", "
			}

			// Value to insert
			value := q.insertVal.Index(rowI).Field(col.position).Interface()

			// If we have a 1:1 reference (which we don't create), the value to insert
			// has to be extracted from the referenced struct
			if col.isForeignKeyReference {
				// Get the referenced column position
				lastDot := strings.LastIndex(col.ForeignKeyReference, ".")
				referencedColumn := col.ForeignKeyReference[lastDot+1:]
				position := -1
				for _, cc := range col.foreignKeyTable.columns {
					if cc.Name == referencedColumn {
						position = cc.position
					}
				}

				// Referenced field not found
				if position == -1 {
					return 0, databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("didn't found referenced column %q in %s", referencedColumn, reflect.ValueOf(value).Type()),
						Response: errors.InternalError(),
					}
				}

				refValue := reflect.ValueOf(value)
				if refValue.Kind() == reflect.Pointer {
					value = refValue.Elem().Field(position).Interface()
				} else {
					value = refValue.Field(position).Interface()
				}
			}

			// We use a default value if the column is not nullable
			// and the user provided a "null" value (go-ddl only sets the field
			// to a sql.Null type if the column is not nullable)
			if col.HasDefaultValue && isZero(value) {
				insert += fmt.Sprintf("DEFAULT(%s)", getColumnIdentifier(&tbls[0], &col))
			} else {
				insert += "?"
				placeholders = append(placeholders, value)
			}

			ii = ii + 1
		}
		insert += ")"
	}

	// Execute the insert (only if we have data to insert)
	insId := int64(0)
	if len(placeholders) > 0 {
		res, err := q.operator.dbUtils.Db.Exec(insert, placeholders...)
		if err != nil {
			logger.Debug("Statement for failed insert:\n%s", insert)
			return 0, databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to insert value: %s", err),
				Response: errors.InternalError(),
			}
		}

		// We will get the ID of the first inserted row (for MariaDB auto increment).
		// The ID of all other rows will ALWAYS be incremented by one (InnoDB)
		insId, _ = res.LastInsertId()

	}
	insIdOrig := insId

	// Insert n:1 relationships
	for _, col := range tbls[0].columns {
		if col.PointedKeyReference == "" || col.foreignKeyTable == nil || !q.columnSelector.PointedKeyReference {
			continue
		}

		// Find the referenced field
		coll := column{}
		for _, cc := range col.foreignKeyTable.columns {
			if getColumnIdentifier(col.foreignKeyTable, &cc) == col.PointedKeyReference {
				coll = cc
				break
			}
		}
		if coll.fieldName == "" || coll.ForeignKeyReference == "" {
			return 0, databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("no referenced field found for %q in %q", col.PointedKeyReference, col.foreignKeyTable.typ),
				Response: errors.InternalError(),
			}
		}

		// Extract the field name to which the foreign key points to
		fieldName := coll.ForeignKeyReference
		lastPoint := strings.LastIndex(fieldName, ".")
		fieldName = structt.GetFieldName(fieldName[lastPoint+1:])

		// Build array with data we need to insert
		insArray := reflect.MakeSlice(reflect.SliceOf(col.foreignKeyTable.typ), 0, 0)

		// If we insert multiple rows at once with AUTO_INCREMENT, we also have multiple
		// primary keys. For MariaDB, they are incremented ALWAYS by once
		insIdCols := insId
		for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
			field := q.insertVal.Index(rowI).Field(col.position)

			// Get identifier of the row we need to set for the foreign key.
			// This HAS TO BE the primary key of the table → use auto_increment
			// if last inserted ID it not zero
			identifier := q.insertVal.Index(rowI).FieldByName(fieldName)
			if insIdCols != 0 {
				identifier = reflect.ValueOf(int(insIdCols))
				insIdCols++
			}

			// Set this identifier for every element
			for i := 0; i < field.Len(); i++ {
				sF := field.Index(i).FieldByName(coll.fieldName)
				sF.Set(identifier)
				insArray = reflect.Append(insArray, field.Index(i))
			}
		}

		// Copy this insert struct to apply customizations
		qCopy := *q
		qCopy.typ = insArray.Type().Elem()
		qCopy.insertVal = insArray
		_, errNew := qCopy.Run()
		if errNew != nil {
			return 0, databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to insert pointed key reference %s: %s", qCopy.typ, errNew),
				Response: errors.InternalError(),
			}
		}
	}

	return insIdOrig, nil
}

// Update statement in a database context
type Update struct {

	// Internal reference to an operator
	operator *StructOperator

	// Fields to exclude to query
	columnSelector ColumnSelector

	// Whether the selector was set
	customSelector bool

	// Type of the struct to insert
	typ reflect.Type

	// Value to insert (slice of types)
	insertVal reflect.Value

	// The last occured error will be stored in this fild and is
	// only returned in "Run()".
	// If any error occured, the (internal) processing is stopped
	err DatabaseError
}

// Update will update a single row of the database.
// A pointer to a struct is expected (*struct).
// Embedded structs are not supported!
func (o *StructOperator) Update(val any) *Update {
	rtc := &Update{
		operator: o,
	}

	// Check for pointer
	if !rtc.columnSelector.isTableStruct(reflect.TypeOf(val)) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to a table struct: %s", reflect.TypeOf(val)),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = reflect.TypeOf(val).Elem()
	rtc.insertVal = reflect.MakeSlice(reflect.SliceOf(rtc.typ), 0, 0)
	rtc.insertVal = reflect.Append(rtc.insertVal, reflect.ValueOf(val).Elem())

	return rtc
}

// UpdateSlice will update a list of rows in the database.
// A pointer to an array is expected (*[]struct).
// Embedded structs are not supported!
func (o *StructOperator) UpdateSlice(val any) *Update {
	rtc := &Update{
		operator: o,
	}

	// Check for pointer
	t := reflect.TypeOf(val)
	if isPointerType(t, reflect.Slice) != nil || !rtc.columnSelector.isArrayToTableStruct(t.Elem()) {
		rtc.err = databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("invalid type for insert value given. Expected a pointer to an array of table structs: %s", t),
			Response: errors.InternalError(),
		}
		return rtc
	}

	rtc.typ = t.Elem().Elem()
	rtc.insertVal = reflect.ValueOf(val).Elem()

	return rtc
}

// Selector sets a custom selector for columns which should be inserted
func (q *Update) Selector(selector ColumnSelector) *Update {
	q.columnSelector = selector
	q.customSelector = true
	q.columnSelector.ForeignKeyReference = false
	return q
}

// Run executes the insert operation and returns all errors
func (q *Update) Run() DatabaseError {
	if q.err != nil {
		return q.err
	}

	// A primary key is needed to identify the row to update
	q.columnSelector.includePrimaryKeys = true

	// Parse all fields. We expect a single table (level != 0)
	tbls, err := q.columnSelector.parseField(q.typ, 1, "")
	if err != nil {
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to parse fields of struct %q: %s", q.typ, err),
			Response: errors.InternalError(),
		}
	}
	if len(tbls) < 1 {
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("no table received form parsing struct"),
			Response: errors.InternalError(),
		}
	}

	// Nothing to insert
	if q.insertVal.Len() == 0 {
		logger.Debug("Got no data to insert for table %q", getTableIdentifier(&tbls[0]))
		return nil
	}

	// We expect exactly a primary key
	primKeys := 0
	primKeyJoin := ""
	for _, c := range tbls[0].columns {
		if c.IsPrimaryKey {
			primKeys++
			primKeyJoin = fmt.Sprintf("ON vals.%s = tbl.%s", c.Name, c.Name)
		}
	}
	if primKeys != 1 {
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("expected to find exactly a single primary key. Found %d", primKeys),
			Response: errors.InternalError(),
		}
	}

	// Build update statement with values
	update := "UPDATE " + getTableIdentifier(&tbls[0]) + " tbl \nJOIN ("
	placeholders := make([]any, 0)
	for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
		ii := 0
		for colI, col := range tbls[0].columns {
			// Syntax preperatiosn
			if colI == 0 {
				if rowI != 0 {
					update += "\n\tUNION ALL"
				}
				update += "\n\tSELECT "
			}

			// Skip pointed key reference
			if col.PointedKeyReference != "" {
				continue
			}

			if ii != 0 {
				update += ", "
			}

			// Value to insert
			value := q.insertVal.Index(rowI).Field(col.position).Interface()

			// If we have a 1:1 reference (which we don't create), the value to insert
			// has to be extracted from the referenced struct
			if col.isForeignKeyReference {
				// Get the referenced column position
				lastDot := strings.LastIndex(col.ForeignKeyReference, ".")
				referencedColumn := col.ForeignKeyReference[lastDot+1:]
				position := -1
				for _, cc := range col.foreignKeyTable.columns {
					if cc.Name == referencedColumn {
						position = cc.position
					}
				}

				// Referenced field not found
				if position == -1 {
					return databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("didn't found referenced column %q in %s", referencedColumn, reflect.ValueOf(value).Type()),
						Response: errors.InternalError(),
					}
				}

				value = reflect.ValueOf(value).Field(position).Interface()
			}

			// We use a default value if the column is not nullable
			// and the user provided a "null" value (go-ddl only sets the field
			// to a sql.Null type if the column is not nullable)
			if col.HasDefaultValue && isZero(value) {
				update += fmt.Sprintf(
					`(SELECT a.def FROM (SELECT COUNT(*), DEFAULT(%s) AS "def" FROM %s) a) AS %q`,
					col.Name, getTableIdentifier(&tbls[0]), col.Name,
				)
			} else {
				update += fmt.Sprintf("? AS %q", col.Name)
				placeholders = append(placeholders, value)
			}

			ii = ii + 1
		}
	}

	// Add join and set statements
	update += "\n) vals " + primKeyJoin + "\n SET "
	ii := 0
	for _, c := range tbls[0].columns {
		if c.IsPrimaryKey || c.PointedKeyReference != "" {
			continue
		}

		// Add colon
		if ii != 0 {
			update += ", "
		}

		// Add set statement
		update += fmt.Sprintf("tbl.%s = vals.%s", c.Name, c.Name)

		ii++
	}

	// Execute the update
	_, err = q.operator.dbUtils.Db.Exec(update, placeholders...)
	if err != nil {
		logger.Debug("Statement for failed update:\n%s", update)
		return databaseErr{
			Typ:      UnexpectedError,
			Err:      fmt.Errorf("failed to update value: %s", err),
			Response: errors.InternalError(),
		}
	}

	// Add n:1 relationships (Delete + Insert again)
	if q.columnSelector.PointedKeyReference {

		// Use transactions if something fails
		transaction, err := q.operator.dbUtils.NewTransaction()
		if err != nil {
			return databaseErr{
				Typ:      UnexpectedError,
				Err:      fmt.Errorf("failed to create transaction for 1:n reference %s", err),
				Response: errors.InternalError(),
			}
		}

		// Find columns we need to update
		for _, col := range tbls[0].columns {
			if col.PointedKeyReference == "" {
				continue
			}

			// Find the referenced field
			coll := column{}
			for _, cc := range col.foreignKeyTable.columns {
				if getColumnIdentifier(col.foreignKeyTable, &cc) == col.PointedKeyReference {
					coll = cc
					break
				}
			}
			if coll.fieldName == "" || coll.ForeignKeyReference == "" {
				return databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("no referenced field found for %q in %q", col.PointedKeyReference, col.foreignKeyTable.typ),
					Response: errors.InternalError(),
				}
			}

			// Get table and column from where to delete the rows from
			delColumnName := col.PointedKeyReference
			delLastPoint := strings.LastIndex(delColumnName, ".")
			delTableName := col.PointedKeyReference[:delLastPoint]
			delStatement := fmt.Sprintf("DELETE FROM %s WHERE %s IN (", delTableName, delColumnName)
			delPlaceholder := []any{}

			// Extract the field name to which the foreign key points to
			fieldName := coll.ForeignKeyReference
			lastPoint := strings.LastIndex(fieldName, ".")
			fieldName = structt.GetFieldName(fieldName[lastPoint+1:])

			// Values to insert again after deleting the old ones
			//insVal := reflect.MakeSlice(reflect.SliceOf(col.foreignKeyTable.typ), 0, 0)

			// Get the
			for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
				identifier := q.insertVal.Index(rowI).FieldByName(fieldName).Interface()
				if rowI != 0 {
					delStatement += ","
				}
				delStatement += "?"
				delPlaceholder = append(delPlaceholder, identifier)

				//insVal = reflect.Append(insVal, q.insertVal.Index(rowI).FieldByName(col.fieldName))
			}
			delStatement += ")"

			// Delete values
			res, err := transaction.Db.Exec(delStatement, delPlaceholder...)
			if err != nil {
				logger.Debug("Failed delete statement:\n%s", delStatement)
				transaction.RollbackTransaction()
				return databaseErr{
					Typ:      UnexpectedError,
					Err:      fmt.Errorf("failed to delete 1:n reference: %s", err),
					Response: errors.InternalError(),
				}
			}
			affectedRows, _ := res.RowsAffected()
			logger.Trace("Deleted %d rows for 1:n update", affectedRows)

			// Insert data again
			//ins := q.operator.InsertSlice(insVal.Addr().Interface())
			ins := q.operator.insertSlice(q.insertVal)
			tmpOperator := *ins.operator
			ins.operator = &tmpOperator
			ins.operator.dbUtils = transaction

			// Only update the field with the 1:n relationship
			//ins.Selector(ColumnSelector{ IncludeColumns: []string{ col.fieldName + "|#" + structt.GetFieldName("") } })
			ins.Selector(ColumnSelector{IncludeColumns: []string{"*|" + delTableName}, PointedKeyReference: true})
			ins.columnSelector.includePrimaryKeys = true
			if _, err := ins.Run(); err != nil {
				transaction.RollbackTransaction()
				return err
			}

			// Build array with data we need to insert

			/*
				insArray := reflect.MakeSlice(reflect.SliceOf(col.foreignKeyTable.typ), 0, 0)

				// If we insert multiple rows at once with AUTO_INCREMENT, we also have multiple
				// primary keys. For MariaDB, they are incremented ALWAYS by once
				insIdCols := insId
				for rowI := 0; rowI < q.insertVal.Len(); rowI++ {
					field := q.insertVal.Index(rowI).Field(col.position)

					// Get identifier of the row we need to set for the foreign key.
					// This HAS TO BE the primary key of the table → use auto_increment
					// if last inserted ID it not zero
					identifier := q.insertVal.Index(rowI).FieldByName(fieldName)
					if insIdCols != 0 {
						identifier = reflect.ValueOf(int(insIdCols))
						insIdCols++
					}

					// Set this identifier for every element
					for i := 0; i < field.Len(); i++ {
						sF := field.Index(i).FieldByName(coll.fieldName)
						sF.Set(identifier)
						insArray = reflect.Append(insArray, field.Index(i))
					}
				}

				// Copy this insert struct to apply customizations
				qCopy := *q
				qCopy.typ = insArray.Type().Elem()
				qCopy.insertVal = insArray
				_, errNew := qCopy.Run()
				if errNew != nil {
					return 0, databaseErr{
						Typ:      UnexpectedError,
						Err:      fmt.Errorf("failed to insert pointed key reference %s: %s", qCopy.typ, errNew),
						Response: errors.InternalError(),
					}
				}
			*/
		}

		transaction.CommitTransaction()
	}

	return nil
}
