version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - embeddedstructfieldcheck
    - forcetypeassert
    - forbidigo
    - funlen
    - funcorder
    - gochecknoglobals
    - gocognit
    - goconst
    - godot
    - godox
    - gosec
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - noinlineerr
    - nonamedreturns
    - nlreturn
    - paralleltest
    - perfsprint
    - protogetter
    - revive
    - spancheck
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5

  settings:
    dupl:
      threshold: 500
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - ifElseChain
      settings:
        hugeParam:
          sizeThreshold: 148
        rangeValCopy:
          sizeThreshold: 256
    govet:
      enable-all: true
      disable:
        - shadow
    nakedret:
      max-func-lines: 0
    staticcheck:
      checks: ["all"]
    gocyclo:
      min-complexity: 35
  exclusions:
    rules:
      - path: _templ.go
        linters:
          - all

      - linters:
          - usestdlibvars
        text: "can be replaced by http.Status"
      - linters:
          - staticcheck
        text: "ST1000: at least one file in a package should have a package comment"
      # Ignore prefered naming of constants and fields like API
      - linters:
          - staticcheck
        text: "ST1003:"
      - linters:
          - govet
        text: "fieldalignment: struct"
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"
      - linters:
          - errcheck
        source: "cmd\\.Wait.*"

      - path: "_test.go"
        linters:
          - errcheck
          - sqlclosecheck

      # For most constants and vars it doesn't make sense to use go naming convention
      - linters:
        - staticcheck
        text: "ST1022: comment on exported const"
      - linters:
        - staticcheck
        text: "ST1022: comment on exported var"
      - linters:
        - godoclint
        text: "godoc should start with symbol name"
      # Templ uses version as package comment
      - linters:
        - godoclint
        text: "package has more than one godoc"

issues:
  fix: true
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 2m