{{- if .Values.httpProxy.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include ".fullname" . }}
spec:
  virtualhost:
    fqdn: {{ .Values.httpProxy.virtualhost.fqdn }}
    tls:
      secretName: {{ .Values.httpProxy.virtualhost.tlsSecretName }}
    authorization:
      authPolicy:
        disabled: true
  routes:
    - conditions:
      - prefix: /
      services:
        - name: {{ include ".fullname" . }}-rpout-service
          port: 4020
      timeoutPolicy:
        response: 30s

  ingressClassName: {{ .Values.httpProxy.ingressClassName }}
{{- end }}