# ArgoCD doesn't support the helm lookup function yet: https://github.com/argoproj/argo-cd/issues/5202.
# So don't prune this secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include ".fullname" . }}-secrets
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
data:
  jwt_key: {{ randAlphaNum 32 | b64enc | quote }}