package table

import (
	icons "git.rpjosh.de/RPJosh/workout/internal/api/components/icon"
	"git.rpjosh.de/RPJosh/workout/internal/translator"
	"github.com/a-h/templ"
)

// Table contains utility functions for creating a generic
// table with various options
type Table struct {
	Tr    *translator.Translator
	Icons *icons.Icons
}

// Options lets you configure the actions and appearance of the table
type Options struct {
	// A unique ID for this table instance
	Id string

	// Headers to use for the table
	Headers []Header

	Delete      Delete
	Edit        Edit
	MoreOptions MoreOptions

	// The default column index to use when resetting sorting
	DefaultSortIndex int

	// Whether the rows should be selectable by clicking on them.
	// You should render a checkbox in each row for this to work properly
	SelectableRows bool
}

// Delete displays a delete icon and automatically removes the
// row from the table for a successful response
type Delete struct {
	Enabled bool

	// Template URL (with a %s inside) to call when the button was clicked
	Url string

	// Translation key to use when hoovering over the delete button
	Hover string

	// Additional attributes to add to the HTMX call
	Attributes templ.Attributes

	// Custom inline function call to execute after deleting the row
	AfterDelete func(id string) string
}

func (d *Delete) GetAfterDelete(id string) string {
	if d.AfterDelete != nil {
		return d.AfterDelete(id)
	}

	return ""
}

type Edit struct {
	Enabled bool

	// This should be a wrapper function around [templ.ModalSpan]
	ModalSpan func(class string, id string) templ.Component

	// Translation key to use when hoovering over the delete button
	Hover string
}

type MoreOptions struct {
	Enabled bool

	// Function to execute when the Button was clicked.
	// This should be generated by [templates.OpenPopup]
	OnClick func(id string) templ.ComponentScript
}

type Header struct {
	// The translation key for the header name
	Name string

	// Additional classnames to add for the "th" elements
	Class string

	// Whether this table column is sortable.
	// By default, the inner text of the "<tr>" element is used as a value.
	// If your row structure is more complex, you can also use "data-compare-value"
	Sortable bool

	// Whether this column should be parsed as a number. Is relevant for sorting
	IsNumber bool
}

// UseActions returns whether the action column is used
func (o *Options) UseActions() bool {
	return o.Delete.Enabled || o.Edit.Enabled || o.MoreOptions.Enabled
}

// GetId returns an uniqued ID based on the table ID and
// the unique entity ID
func (o *Options) GetId(entityId string) string {
	return o.Id + "-tr-" + entityId
}
