// Package dbstruct contains database operations (query + dml) that are based on struct
// fields and tags genereted by the go-ddl parser
package dbstruct

import (
	"fmt"
	"reflect"
	"strings"

	"git.rpjosh.de/RPJosh/workout/pkg/database"
	"git.rpjosh.de/RPJosh/workout/pkg/errors"
	"github.com/RPJoshL/go-ddl-parser/structt"
)

type OrderByOrder string

const (
	ASC  OrderByOrder = "ASC"
	DESC OrderByOrder = "DESC"
)

// Operator contains extended functions for "DatabaseUtils"
// to query, update or delete structs generated by "go-ddl-parser"
// or manually tagged structs
type Operator struct {
	// Internal reference to the DatabaseUtils
	dbUtils database.Dbler
}

func NewOperator(dbUtils database.Dbler) *Operator {
	return &Operator{
		dbUtils: dbUtils,
	}
}

// ColumnSelector specifies which columns should be selected or updated
type ColumnSelector struct {

	// Only include the specified columns.
	// The value should be a const expressiong generated by go-ddl
	IncludeColumns []string

	// Columns to exclude
	ExcludeColumns []string

	// Whether to include foreignKeyReferences (1:1 relationships).
	//   - Select: enabled by default
	//   - Insert: disabled by default
	//   - Update: disabled by default. The old data will not be removed
	ForeignKeyReference bool

	// Whether to include columns that references this row
	// (n:1 relationships)
	PointedKeyReference bool

	// By default all pointed key references are fetched in a single select and
	// are mapped back by their value.
	// When setting this option, a select for every struct is executed asynchroniously.
	//
	// This option is recommended if the resulting size would be > 50.000 data points
	PointedKeyReferenceAsync bool

	// Whether primary keys should always be parsed
	includePrimaryKeys bool
}

// Where contains data for a specific where statement
type Where struct {

	// Internal reference to the query
	query *Query

	// Operator like "=", ">", "<", ...
	operator string

	// Column name to select
	column string

	// Value to insert as a placeholder
	val any

	// Ignore the case
	ignoreCase bool

	// Custom where statement to append to the query
	customWhere string
	// Custom values to append to the query
	customValue []any
}

type table struct {
	structt.MetadataTag

	// Type of this struct
	typ reflect.Type

	// Columns of this table
	columns []column

	// Only for level zero and multiple (embedded) tables
	fieldName string
}

type column struct {
	structt.ColumnTag

	// Position of the field within struct type
	position int

	// Table that is referenced by this column. It's filled when:
	//   - isForeignKeyReference = treu
	//   - [structt.ColumnTag.PointedKeyReference != ""]
	foreignKeyTable *table

	// Whether this field points to another struct that
	// is referenced via a foreign key.
	// We need this additional field besides [structt.ColumnTag.ForeignKeyReference] to
	// check if the go ddl-parser actually used a full struct instead
	// of only the primary key from the referenced table
	isForeignKeyReference bool

	// Name of the struct field the column is assigned to
	fieldName string
}

// parseField parses all fields of the provided struct{}.
// For a level != 0 this function always returns a single table
func (s ColumnSelector) parseField(val reflect.Type, level int, structField string) (rtcTbl []table, e error) {
	// Table structs are identified by the metadata field.
	// Because we also get embedded fields in [FieldByName()], we check the index path
	if f, found := val.FieldByName(structt.MetadataFieldName); found && len(f.Index) == 1 {
		valTag, ok := f.Tag.Lookup(structt.MetadataTagId)
		if !ok {
			e = fmt.Errorf("no tag found for metadata in %s", val)
			return
		}

		// Tbl metadata
		tbl := table{
			MetadataTag: *structt.FromMetadataTag(valTag),
			typ:         val,
			fieldName:   structField,
		}

		for i := range val.NumField() {
			field := val.Field(i)

			// Get tag
			valTag, ok := field.Tag.Lookup(structt.ColumnTagId)
			if !ok {
				continue
			}

			col := column{
				ColumnTag: *structt.FromColumnTag(valTag),
				position:  i,
				fieldName: field.Name,
			}

			// Check if column is ignored
			if s.isFieldIgnored(&tbl, &col) {
				continue
			}

			// Set any foreign key reference
			if col.ForeignKeyReference != "" && s.isTableStruct(field.Type) {
				col.isForeignKeyReference = col.ForeignKeyReference != ""
				tbll, err := s.parseField(field.Type.Elem(), level+1, "")
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}

				// We receive exactly a single table for a foreign key
				col.foreignKeyTable = &tbll[0]
			} else if col.PointedKeyReference != "" && s.isArrayToTableStruct(field.Type) {
				tbll, err := s.parseField(field.Type.Elem(), level+1, "")
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}

				// We receive exactly a single table for a foreign key
				col.foreignKeyTable = &tbll[0]
			}

			// Add column
			tbl.columns = append(tbl.columns, col)
		}

		rtcTbl = append(rtcTbl, tbl)
	} else if level == 0 {
		// For level 0 we search also for "embedded structs"
		for i := range val.NumField() {
			field := val.Field(i)

			if s.isEmbeddedTableStruct(field.Type) {
				tbll, err := s.parseField(field.Type, level+1, field.Name)
				if err != nil {
					e = fmt.Errorf("failed to parse fields of referenced struct %q (from %q)", field.Type, val)
					return []table{}, e
				}
				rtcTbl = append(rtcTbl, tbll...)
			}
		}
	}

	return
}

// isFieldIgnored checks whether this field should be ignored
func (s ColumnSelector) isFieldIgnored(tbl *table, col *column) bool {
	// Always return primary keys
	if s.includePrimaryKeys && col.IsPrimaryKey {
		return false
	}

	// Get tag identifier we are looking for
	fieldIdentifier := structt.GetFieldName(col.Name) + "|" + getColumnIdentifier(tbl, col)

	// If we have a positive selection of fields, ignore all other fields
	if len(s.IncludeColumns) != 0 {
		include := false
		for _, f := range s.IncludeColumns {
			if fieldIdentifier == f {
				include = true
				break
			}

			// Check if wildcard matches
			if f == "*|"+tbl.Schema+"."+tbl.Table || f == "*|"+tbl.Table {
				include = true
				break
			}

			// We always include this field if it's a 1:n relationship and was included in
			// columns to include
			if col.PointedKeyReference != "" {
				lastDot := strings.LastIndex(col.PointedKeyReference, ".")
				pTable := col.PointedKeyReference[:lastDot]
				pColumn := col.PointedKeyReference[lastDot+1:]

				// Get directly
				// pDirect := col.fieldName + "|#" + pTable + "." + structt.GetFieldName(pColumn)
				pDirect := col.fieldName + "|#" + getColumnIdentifier(tbl, col) + col.fieldName
				if f == pDirect {
					include = true
					break
				}

				// Get by referenced sub id
				pIndirect := structt.GetFieldName(pColumn) + "|" + col.PointedKeyReference
				if f == pIndirect || strings.HasSuffix(f, "|"+pTable) {
					include = true
					break
				}
			}
		}

		if !include {
			return true
		}
	}

	for _, f := range s.ExcludeColumns {
		if f == fieldIdentifier {
			return true
		}

		// Check if wildcard matches
		if f == "*|"+tbl.Schema+"."+tbl.Table || f == "*|"+tbl.Table {
			return true
		}
	}

	return false
}

// isTableStruct checks weather val is a pointer to a struct
// that contains a DbMetadata field and is therefore referenced
// as a "table" struct
func (s ColumnSelector) isTableStruct(val reflect.Type) bool {
	// Pointer to a struct required
	if err := isPointerType(val, reflect.Struct); err != nil {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.Elem().FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// isTableStruct checks weather val is a struct
// that contains a DbMetadata field and is therefore referenced
// as a "table" struct
func (s ColumnSelector) isEmbeddedTableStruct(val reflect.Type) bool {
	// Struct type required
	if val.Kind() != reflect.Struct {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// isArrayToTableStruct checks weather val is an array to a struct
// type that contains a DbMetadata field
func (s ColumnSelector) isArrayToTableStruct(val reflect.Type) bool {
	if val.Kind() != reflect.Slice {
		return false
	}

	// Check if struct contains metadata tab
	if _, found := val.Elem().FieldByName(structt.MetadataFieldName); found {
		return found
	}

	return false
}

// Where returns a new selection condition for the query.
// All single where statements are concatenated by a logical AND
func (q *Query) Where() *Where {
	return &Where{
		query: q,
	}
}

// Column sets the expression for the provided database column.
//
// The column can either be a raw column name in format table.column
// without a "|", or a const expression generated by go-ddl.
//
// The operator has to be a valid sql operator like "=", ">", "<", IN ...
func (w *Where) Column(columnName, operator string, value any) *Where {
	if strings.Count(columnName, "|") == 1 {
		// Const's expression provided
		pipe := strings.Index(columnName, "|")
		w.column = columnName[pipe+1:]
	} else {
		w.column = columnName
	}

	// Set values
	w.operator = operator
	w.val = value

	return w
}

// IgnoreCase sets whether the case of a string column
// should be ignored.
//
// The query will error if the column or value are not a
// string
func (w *Where) IgnoreCase(ignore bool) *Where {
	w.ignoreCase = true
	return w
}

// Add adds this where statemen to the query
func (w *Where) Add() *Query {
	// Process custom where statement
	if w.customWhere != "" {
		w.query.whereStatement += "\tAND (" + w.customWhere + ")\n "
		w.query.wherePlaceholder = append(w.query.wherePlaceholder, w.customValue...)

		return w.query
	} else if w.column == "" {
		return w.query
	}

	// Parse custom statement
	w.operator = strings.ToUpper(w.operator)
	switch w.operator {
	case "IN", "NOT IN":
		refVal := reflect.ValueOf(w.val)

		// Validate type
		if refVal.Type().Kind() != reflect.Slice {
			w.query.err = database.DatabaseError{
				Typ:      database.UnexpectedError,
				Err:      fmt.Errorf("expected an array for 'IN' / 'NOT IN' statement. Got type %s", refVal.Type().Kind()),
				Response: errors.InternalError(),
			}
			return w.query
		}

		// Loop through every field
		w.query.whereStatement += fmt.Sprintf("\tAND %s %s (", w.column, w.operator)
		for i := range refVal.Len() {
			if i != 0 {
				w.query.whereStatement += ", "
			}

			if w.ignoreCase {
				w.query.whereStatement += "LOWER(?)"
			} else {
				w.query.whereStatement += "?"
			}

			w.query.wherePlaceholder = append(w.query.wherePlaceholder, refVal.Index(i).Interface())
		}
		w.query.whereStatement += ")\n"
		return w.query
	}

	// Default processing
	if w.ignoreCase {
		w.query.whereStatement += fmt.Sprintf("\tAND LOWER(%s) %s LOWER(?)\n", w.column, w.operator)
	} else {
		w.query.whereStatement += fmt.Sprintf("\tAND %s %s ?\n", w.column, w.operator)
	}

	w.query.wherePlaceholder = append(w.query.wherePlaceholder, w.val)

	return w.query
}

// getColumnName returns the full reference of a column
// (schema.table.column)
func getColumnIdentifier(tbl *table, col *column) string {
	identifier := tbl.Table + "." + col.Name
	if tbl.Schema != "" {
		identifier = tbl.Schema + "." + identifier
	}

	return identifier
}

// getTableIdentifier returns the full reference of a table
// (schema.table)
func getTableIdentifier(tbl *table) string {
	rtc := tbl.Table
	if tbl.Schema != "" {
		rtc = tbl.Schema + "." + tbl.Table
	}

	return rtc
}
